stakira/OpenUtau

OpenUtau/Core/Classes/PlaybackManager.cs, OpenUtau/Core/Render/NAudio/AudioStreamReader.cs, OpenUtau/Core/Render/NAudio/CachedSound.cs, OpenUtau/Core/Render/RenderItem.cs.bak, OpenUtau/Core/Render/ResamplerInterface.cs.bak, OpenUtau/Core/ResamplerDriver/DriverEngine.cs, OpenUtau/Core/ResamplerDriver/DriverModels.cs, OpenUtau/Core/ResamplerDriver/DriverModels.cs.bak, OpenUtau/Core/ResamplerDriver/Factorys/CppDriver.cs, OpenUtau/Core/ResamplerDriver/Factorys/ExeDriver.cs, OpenUtau/Core/ResamplerDriver/Factorys/SharpDriver.cs, OpenUtau/Core/Util/IniFileClass.cs, OpenUtau/OpenUtau.csproj
Make ResamplerDLL Engine into master
=> Add ResamplerInterface andSolt

OpenUtau/Core/Formats/UtauSoundbank.cs
Create singer URI correctly. Fixes #17
=> fix URI issue

OpenUtau/UI/Strings.ko-KR.xaml
something is not translated.. so i fixed them
=> korean translate

OpenUtau/UI/Strings.ja-JP.xaml
Localized into Japanese. / 日本語にローカライズしました。
=> Strings.ja-JP.xaml

OpenUtau/UI/Strings.ja-JP.xaml
=> Missing > on line 94

OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
Removes unfinished presamp.ini support
=> Revert changes to JA CVVC Phonemizer

OpenUtau.App/Strings/Strings.es-MX.axaml
Fixed grammar. Translated Legacy Plugins, Select Singer, and Tags. Translated the Update section.
=> Updated Translation

OpenUtau/Strings/Strings.es-MX.axaml
Translated batch lyric edit section.
=> Updated Translation.

OpenUtau.Core/Render/RenderEngine.cs, OpenUtau.Core/ResamplerDriver/DriverModels.cs
i suppose it was removed long ago when there were no expressions?
=> bring back Modulation

OpenUtau.Plugin.Builtin/PolishCVCPhonemizer.cs, OpenUtau.Plugin.Builtin/RussianCVCPhonemizer.cs, OpenUtau.Plugin.Builtin/RussianVCCVPhonemizer.cs, OpenUtau.Plugin.Builtin/SyllableBasedPhonemizer.cs
some helper code in help for beginner programmers & usage in my phonemizers
=> some syntax sugar for SyllableBasedPhonemizer

OpenUtau.Plugin.Builtin/PolishCVCPhonemizer.cs, OpenUtau.Plugin.Builtin/RussianCVCPhonemizer.cs, OpenUtau.Plugin.Builtin/RussianVCCVPhonemizer.cs, OpenUtau.Plugin.Builtin/SyllableBasedPhonemizer.cs
=> possibility to allow alias extension on syllable extension 

OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
* phonemizer will now try to adjust next neighbor when alias is input directly (useful for banks that implement extra features like glottal stops and vocal fry)
=> KO VCV Phonemizer update

OpenUtau.Plugin.Builtin/EnglishDeltaPhonemizer.cs
Currently supports Kasane Teto and Peiton.
Support for other Delta English reclists is not done yet.
Much help from @HeidenBZR
=> [WIP/Merge OK] English Delta Phonemizer

OpenUtau/Strings/Strings.es-MX.axaml
=> Updated translation!

OpenUtau/Strings/Strings.es-MX.axaml
Minor grammatical fixes to the "log resamplers" feature
=> Revised Translation

OpenUtau/Strings/Strings.fr-FR.axaml
French Translation Update - Small tweaks to existing translation (grammar errors) + translated new prompts that were still in English
=> French Translation Update

OpenUtau.Plugin.Builtin/ArpasingPhonemizer.cs
=> Force alias with ? prefix

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/Strings/Strings.ko-KR.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/Styles/Styles.axaml
MS font spec - https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-fonts
Mac font spec - https://support.apple.com/guide/pages/format-chinese-japanese-or-korean-text-tanfbd4156e/mac
=> Added font localization (especially CJK)

OpenUtau.Core/Util/Preferences.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/ViewModels/NotesViewModel.cs, OpenUtau/ViewModels/PreferencesViewModel.cs, OpenUtau/ViewModels/TracksViewModel.cs, OpenUtau/Views/PreferencesDialog.axaml
This PR implements these two features as requested by #235:
1. Backward auto-scroll
2. An option to disable auto-scroll
Closes #235
=> Auto-scroll enhancements

OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs
In long:
* Full VCV support:
* Automatic "ny" instead of "nh";
* Automatic "s" instead of "z" (seseo);
* Automatic "i" instead of "y";
* Automatic "u" instead of "w";
* "n" for substitute-"ny" now works for CC-transitions between syllables;
* Necessary consonant clusters now always work, even with "i" and "u" (not tested yet with VCV due to a lack of voicebanks that support it);
* Made code more concise and cut the bloat.
Now the phonemizer should be mostly functioning as it should. Still, feedback is welcome.
=> [Spanish Phonemizer] Added full VCV support + seseo + substitutes

OpenUtau.Plugin.Builtin/FrenchCVVCPhonemizer.cs
- Reworked CCV, VCC & CC behaviour
- Now compatible with native/converted Petit Mot (CVVC), Gros Mot (VCV-VC) & Fraloids (CVVC/CVVC+)
Please report any issue to the Discord server if you find one.
=> FR CVVC Refactored - now compatible with both Mots + Fraloids utaus

OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
Improved CCV & VCC behaviour + added new VV behaviour + cleared up VC exceptions & ao conflicts + added "V CC" and "VC CC" + fixed multipitch suffix breaking the VCV transitions with more than one consonant
=> Improved overall logic of EN VCCV phonemizer + fixed multipitch issue

OpenUtau.Plugin.Builtin/FrenchCVVCPhonemizer.cs
Last update, sorry about the delayed pushes.
=> Added CC- and _CV support to French CVVC Phonemizer

OpenUtau.Plugin.Builtin/VietnameseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/VietnameseVCVPhonemizer.cs
Changed the algorithm to make it suitable for Vietnamese
=> Update Vietnamese VCV/CVVC Phonemizer

OpenUtau.Plugin.Builtin/VietnameseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/VietnameseVCVPhonemizer.cs
It's so bad that I found a few small bugs and I kept fixing it
=> Fix some phoneme Vietnamese CVVC/VCV phonemizer

OpenUtau.Plugin.Builtin/VietnameseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/VietnameseVCVPhonemizer.cs
Update Vietnamese CVVC/VCV Phonemizer
=> Vietnamese CVVC/VCV Phonemizer

OpenUtau/Strings/Strings.ko-KR.axaml
한국어 번역을 추가 하였습니다.
Added Korean translation.
=> fix: Korean translation added

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs, OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
[DONE] TODO: proper CC support for 3 consonants
=> [EN Delta Phonemizers] Bug fix related to VC ending stop consonants + substitute VVs + Peiton phoneme support + CC bug fixes

OpenUtau.Core/Util/Preferences.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/ViewModels/NotesViewModel.cs, OpenUtau/ViewModels/PreferencesViewModel.cs, OpenUtau/Views/PreferencesDialog.axaml
=> Add an option to globally disable portrait (still shows portrait by default)

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs, OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
Detailed version:
* Ending VCC support
* Support for ending CC up to 3 consonants (with fallbacks)
* Improved (V)CC handling
* Vowel overhaul; removed unused phonemes
=> [English Delta Phonemizers] Added ending VCC + tweaked (V)CC handling + vowel overhaul

OpenUtau/Strings/Strings.th-TH
String THAI language translation by ARUN0017
=> String THAI language

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs, OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs, OpenUtau.Plugin.Builtin/ItalianSyllableBasedPhonemizer.cs
You can already download the OpenUtau Italian Dictionary [here](https://github.com/lottev1991/OpenUtau-Italian-Dictionary).
**IMPORTANT:** This is **NOT** the same as the Italian CVVC Phonemizer, since that one is very simplistic and doesn't use a dictionary. However, they are both based on Makkusan's reclist.
**TODO:** Add support for falling diphthongs in open syllables. (I have no clue yet how I'm going to do this.)
As for the Delta English phonemizers, I've simply tweaked the way they handle CC transitions a little bit. (This seems to be an ongoing project of mine.)
Bug reports appreciated!
=> [Multiple phonemizers] Add Italian Syllable-Based Phonemizer (+dict link in comment) + small Delta phonemizers tweak

OpenUtau/OpenUtau.csproj, OpenUtau/ViewModels/NoteSelectionViewModel.cs, OpenUtau/ViewModels/NotesViewModel.cs, OpenUtau/ViewModels/PianoRollViewModel.cs, OpenUtau/Views/NoteEditStates.cs, OpenUtau/Views/PianoRollWindow.axaml.cs
*Edit: Accidentally added this PR onto bump of Avalonia version - added bump in separate [PR](https://github.com/stakira/OpenUtau/pull/452).*
This change introduces NoteSelectionViewModel, intended to make atomic changes to selection easier. It wraps up logic that will be used for keyboard-based navigation/range select. Relevant code points of existing mouse functionality also updated.
=> Refactor Note Selection

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/ViewModels/SingersViewModel.cs, OpenUtau/Views/SingersDialog.axaml, OpenUtau/Views/SingersDialog.axaml.cs
=> Add a button to visit singer's website

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs, OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
**TODO for future PR:** Allow for affricate splits in Version 2? (This will be fun...)
=> [English Delta Phonemizers] VC(C) transitions fix

OpenUtau.Core/Format/MidiWriter.cs, OpenUtau.Core/OpenUtau.Core.csproj, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/Views/MainWindow.axaml, OpenUtau/Views/MainWindow.axaml.cs
The encoding of exported midi files is UTF-8.
=> Midi Export

OpenUtau.Plugin.Builtin/FrenchVCCVPhonemizer.cs
French VCCV phonemizer compatible with the word-based m2RUg reclist (X-SAMPA aliasing).
More info on the reclist here https://www.youtube.com/watch?v=YymXCfGsZPs
=> French VCCV m2RUg phonemizer (word-based X-SAMPA reclist)

OpenUtau.Plugin.Builtin/FrenchVCCVPhonemizer.cs
=> French VCCV Phon - Added 'n +j' -> 'J' & fixed wrong _CVs notes.

OpenUtau.Plugin.Builtin/FrenchCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/FrenchVCCVPhonemizer.cs
=> Added FrenchG2p phonetic assistant support to the French phonemizers

OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
This is a lighter version of the phonemizer (it doesn't add as many CCs and is closer to the Lyric Parser method)
+ added symbols for custom dictionary support
=>  English VCCV phonemizer logic should be closer to Lyric Parser now

OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
- `h` should fall back to `hh` now
- missing consonants after "st" or "sp" sounds
- added glides with soft consonants
- fixed `3 C` missing sounds
=> Fixed common issues with EN VCCV Phonemizer

OpenUtau.Core/Classic/VoicebankInstaller.cs
This pull request solves issue #535.
=> Prevent from zip slip attack / 防范zip上级文件夹攻击

OpenUtau.Core/Enunu/EnunuEnglishPhonemizer.cs, OpenUtau.Core/Enunu/EnunuPhonemizer.cs
ENUNU phonemizer hashes: take phoneticHint into account
=> Fix ENUNU EN phonemizer not responding to phoneticHint, singer and phonemizer changes / 修复ENUNU EN音素器不响应方括号音素修改、歌手更换、音素器更换的bug

OpenUtau.Core/PlaybackManager.cs, OpenUtau.Core/Render/RenderEngine.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/Views/MainWindow.axaml, OpenUtau/Views/MainWindow.axaml.cs
Suggested in https://discord.com/channels/551606189386104834/1024455153220329492/threads/1026533351340920852
=> Export the whole project into a single wav file / 混缩导出为单个wav文件

OpenUtau.Core/DefaultPhonemizer.cs
Fixing https://twitter.com/Crescent___P/status/1595502543408402443
=> default phonemizer: support voice color / 默认音素器支持多音色

OpenUtau.Core/Format/Formats.cs, OpenUtau.Core/Format/MidiWriter.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/ViewModels/MainWindowViewModel.cs, OpenUtau/Views/MainWindow.axaml, OpenUtau/Views/MainWindow.axaml.cs
fixing incomplete midi import:  https://discord.com/channels/551606189386104834/801525671775043625/1044418840093786112
=> new midi importer using drywetmidi / 使用drywetmidi导入midi文件

OpenUtau.Plugin.Builtin/KoreanCBNNPhonemizer.cs
=> Add KoreanCBNNPhonemizer

OpenUtau/Controls/TrackHeader.axaml, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/ViewModels/TrackHeaderViewModel.cs
This feature was suggested in https://discord.com/channels/551606189386104834/1054361270012366868
=> support duplicating track or track settings / 支持复制整个音轨或音轨设置

OpenUtau.Core/Commands/ExpCommands.cs, OpenUtau/Views/NoteEditStates.cs, OpenUtau/Views/PianoRollWindow.axaml.cs
adds expression line drawing
https://user-images.githubusercontent.com/45115987/215006806-863464f7-00e7-4b21-9c06-969dae92b7a5.mp4
=> expression line draw

OpenUtau.Core/Format/Formats.cs, OpenUtau.Core/Format/MidiWriter.cs
When importing a midi file as a new project, OpenUtau will import tempos from it
=> import tempos from midi

OpenUtau.Plugin.Builtin/SpanishMakkusanPhonemizer.cs
This phonemizer is to make Italian voicebanks using Makkusan's reclist sing in Spanish, if they have the proper sounds recorded.
- Once merged, updating the Spanish dictionary will be required for the phonemizer to function properly. Currently, there's a [preview branch](https://github.com/lottev1991/OpenUTAU-Spanish-Dictionary/tree/preview) available.
=> Add Spanish Makku-san Phonemizer

OpenUtau.Plugin.Builtin/SpanishVCCVPhonemizer.cs
- Once merged, updating the Spanish dictionary will be required for the phonemizer to function properly. Currently, there's a [preview branch](https://github.com/lottev1991/OpenUTAU-Spanish-Dictionary/tree/preview) available.
=> Add Spanish VCCV (nJokis) Phonemizer

OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs
- Consonant cluster optimization.
- General Code optimization; there's still bloat, but trying to fix it didn't help for now.
- Burst consonant functionality has been removed, as it was deemed unnecessary.
- Once this PR is merged, updating the Spanish dictionary will be necessary. Currently, there's a [preview branch](https://github.com/lottev1991/OpenUTAU-Spanish-Dictionary/tree/preview) available.
- Support for CV fallbacks for standalone consonants has been removed, due to giving issues. It's **highly recommended** to change this in the voicebank's oto if necessary, such as in the case of missing consonants/CC transitions.
- ``[v]rr`` notes support has been removed for the single ``r`` phoneme, as it was causing bugs.
=> [Spanish Syllable-Based Phonemizer] Code refactor + refit for new dictionary + breaking changes (!! PLEASE READ !!)

OpenUtau.Plugin.Builtin/ItalianSyllableBasedPhonemizer.cs
=> [Italian Syllable-Based Phonemizer] Breath note bug fix

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
- Code refactor.
- New consonant ending type.
=> [EN Delta V1 Phonemizer] Code refactor + new consonant ending

OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
- Code refactor.
- New consonant ending type.
=> [EN Delta V2 Phonemizer] Code refactor + new consonant ending type

OpenUtau.Plugin.Builtin/SpanishMakkusanPhonemizer.cs
The bug affects ``rry`` and ``rrw`` clusters.
=> [Spanish Makkusan Phonemizer] CC bug fix + minor code optimization

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
I am currently investigating a better method to implement custom vowels in the user dictionary. However, for now, this will do.
As the issue was mostly affecting diphthongs, Version 2 of the Delta phonemizer currently remains unchanged.
I'm also still planning to work on relevant phonemizer tests.
=> [EN Delta V1 Phonemizer] Add new vowel sounds

OpenUtau.Plugin.Builtin/Data/xsampa.template.yaml
=> [xsampa.template.yaml] Add new vowel sounds

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
Fixes an issue regarding ``[V C]`` + ``[C -]`` fallback endings.
=> [EN Delta V1] Ending consonant fallback fix

OpenUtau.Plugin.Builtin/VietnameseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/VietnameseVCVPhonemizer.cs, OpenUtau.Plugin.Builtin/VietnameseVINAPhonemizer.cs
Update CVVC/VCV Vietnamese Phonemizer
New VINA Vietnamese Phonemizer for new Vietnamese Reclist
=> Update CVVC/VCV, new VINA Vietnamese Phonemizer

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
Fixes a bug related to certain VCC endings.
=> [EN Delta V1] VCC ending fix

OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
Fixes a bug related to certain VCC endings.
Similar to #644.
=> [EN Delta V2] VCC ending fix

OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
It's rare, but I've encountered it, which is why I'd like to add support for it.
=> [JA CVVC Phonemizer] Add non-vowel crossfade CV support

OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
* Added "Japanese presamp Phonemizer"
* Fixed "Japanese CVVC Phonemizer", bug fix on VC length.
=> Add "Japanese presamp Phonemizer" JP VCV & CVVC

OpenUtau.Core/Editing/NoteBatchEdits.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/ViewModels/PianoRollViewModel.cs
An editing macro that converts PITD to pitch points is added.
=> Pitch Baking

OpenUtau.Core/Format/MidiWriter.cs
Added support for importing time signatures when opening a MIDI file as a new project with "File->Open".
Added support for exporting time signatures when exporting a project to a MIDI file.
=> Support importing and exporting time signatures in MIDI files

OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
- Added support for every X-SAMPA vowel in existence, just in case. Some of them include:
- Canadian English diphthongs;
- Some nasalized and rhotic vowels;
- Vocaloid SAMPA vowels;
- Extended ValidateAlias vowel support.
- Fixed some bugs regarding VVs and ending VCs.
=> [EN Delta V1] Add more X-SAMPA vowels + some bug fixes

OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
Similar to #663, with the addendum that the new diphthongs split automatically.
=> [EN Delta V2] Add more X-SAMPA vowels + some bug fixes

OpenUtau.Core/Commands/Notifications.cs, OpenUtau.Core/PlaybackManager.cs, OpenUtau.Core/Render/RenderEngine.cs, OpenUtau.Core/SignalChain/Fader.cs, OpenUtau.Core/Ustx/UTrack.cs, OpenUtau.Core/Util/MusicMath.cs, OpenUtau/Controls/TrackHeader.axaml, OpenUtau/Controls/TrackHeader.axaml.cs, OpenUtau/ViewModels/TrackHeaderViewModel.cs
Issue: https://github.com/stakira/OpenUtau/issues/543
Made a stereo panning slider :)
It works similar to volume. Right click sets to zero (mid).
Made the panning using fader.
Not a C# dev so expect dumb code. Will do my best to fix it.
*I **really** want this feature...*
=> feat: stereo panning slider

OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs
Fixes accidental "double-cluster" bug.
=> [ES SYL Phonemizer] Starting CCV bug fix

OpenUtau.Plugin.Builtin/SpanishVCCVPhonemizer.cs
Fixes some bugs regarding starting CCV notes.
=> [ES VCCV Phonemizer] Starting CCV bug fix

OpenUtau/App.axaml.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Views/PreferencesDialog.axaml
- Fix text was not binding to resources
- Fixed a bug that caused the language to run in the same language as InstalledUICulture the first time it was launched, but reset to en-US when the preference window was opened
=> Fix around language

OpenUtau.Core/Classic/Presamp.cs, OpenUtau.Core/Classic/VoicebankConfig.cs, OpenUtau.Core/Classic/VoicebankLoader.cs, OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs, OpenUtau.Plugin.Builtin/PresampSamplePhonemizer.cs, OpenUtau.Test/Classic/VoicebankConfigTest.cs
- Add PresampSamplePhonemizer (Sample for developers. Not included in release build)
- VCPAD support in JapanesePresampPhonemizer
=> Add PresampSamplePhonemizer and fixes

OpenUtau.Plugin.Builtin/VietnameseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/VietnameseVCVPhonemizer.cs, OpenUtau.Plugin.Builtin/VietnameseVINAPhonemizer.cs
Fixed codes that prevented Phonemizer from using Voice Color
=> Update Vietnamese Phonemizer

OpenUtau.Test/Classic/PluginRunnerTest.cs
I did https://github.com/stakira/OpenUtau/pull/669 .
But this unit test code was wrong.
So I fixed it to exact test.
This bug affect unit test only.
It does not affect the processing of the main.
Could you merge in the next update, please?
=> fix: unit test of PluginRunner

OpenUtau.Plugin.Builtin/JapaneseVCVPhonemizer.cs
=> Revert "[JA VCV] Add alternate support"

OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
=> Revert "[JA CVVC] Add alternate support"

OpenUtau.Plugin.Builtin/SpanishVCCVPhonemizer.cs
Even though the SBP API can't read from oto values, I've decided to implement something that should work okay. It's not the same, but it's better than nothing.
Also fixing a small ``ValidateAlias()`` issue.
=> [Spanish VCCV Phonemizer] Add different consonant lengths support

OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
This is a re-submit of #733. It was working just fine, but I had tested it on the wrong voicebank. Apologies!
---
This function also exists in the Presamp phonemizer.
Sometimes, voicebanks might have voice colors that are in plain CV rather than CVVC (e.g whisper/unvoiced, death growl/screamo). With this function, it can read the CV voice color without defaulting to the base CVVC voice color.
**TODO:** Port function to VCV phonemizer (future PR).
=> [JA CVVC] Read CV append voice color

OpenUtau.Plugin.Builtin/SpanishVCCVPhonemizer.cs
- Add rare ending VCC support;
- Optimized syllabic consonant support;
- Optimized ``ValidateAlias()``;
- Optimized CC support.
=> [ES VCCV] Code and function optimization

OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs
- Optimizes starting CCV notes.
- Optimizes VV notes.
=> [ES SYL] Starting CCV + VV transition fix

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.es-ES.axaml, OpenUtau/Strings/Strings.es-MX.axaml, OpenUtau/Strings/Strings.fi-FI.axaml, OpenUtau/Strings/Strings.fr-FR.axaml, OpenUtau/Strings/Strings.id-ID.axaml, OpenUtau/Strings/Strings.it-IT.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/Strings/Strings.ko-KR.axaml, OpenUtau/Strings/Strings.nl-NL.axaml, OpenUtau/Strings/Strings.pl-PL.axaml, OpenUtau/Strings/Strings.pt-BR.axaml, OpenUtau/Strings/Strings.ru-RU.axaml, OpenUtau/Strings/Strings.th-TH.axaml, OpenUtau/Strings/Strings.vi-VN.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/Strings/Strings.zh-TW.axaml
- Delete unused text
- Uniformity of indentation
- Reflects untranslated text in each language
This PR includes #730.
=> fix translations

OpenUtau/ViewModels/PreferencesViewModel.cs, OpenUtau/Views/PreferencesDialog.axaml
- Preferences dialog on/off to toggle switch
- Created a margin between each element
=> Fix Preferences dialog

OpenUtau.Core/PlaybackManager.cs, OpenUtau.Core/Ustx/UProject.cs, OpenUtau.Core/Ustx/UTrack.cs, OpenUtau/Controls/TrackHeader.axaml, OpenUtau/Controls/TrackHeaderCanvas.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/ViewModels/TrackHeaderViewModel.cs, OpenUtau/ViewModels/TracksViewModel.cs, OpenUtau/Views/MainWindow.axaml.cs, OpenUtau/Views/PianoRollWindow.axaml.cs
New features:
- Solo additionally (which not removes solo from other tracks)
- Unsolo all
- Mute this only
- Mute all others
- Unmute all
UI fix:
- Freeze volume and pan when track is muted
- Mute button works independently of solo
Specification:
- When a track is mute and solo, priority is given to the solo
=> Fix solo and mute

OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
A VC fallback for CV notes starting with "my" was missing, so I added it.
=> [JA CVVC & JA Presamp] Add "m" consonant fallback

OpenUtau.Core/Enunu/EnunuEnglishPhonemizer.cs, OpenUtau.Plugin.Builtin/LatinDiphonePhonemizer.cs
After this change, EN ARPA and ENUNU EN support extending syllables with `+~` or `+*`. This enhances their compatibility with SyllableBasedPhonemizer like EN VCCV.
The "+number" method to distribute phonemes still works as before.
=> EN ARPA and ENUNU EN: support extending syllables with +~ or +*

OpenUtau/Controls/TrackHeader.axaml, OpenUtau/Controls/TrackHeader.axaml.cs
* Adjustment of track header layout
* Allow input of volume and pan values
* Because the slider is difficult to operate.
* To be able to make fine adjustments.
* Add controls to TrackHeader.axaml
* Added show, hide, and input handling to TrackHeader.axaml.cs
* Layout is not very clear.
* Program implementation is simple, but lacks maintainability.
* Might be inefficient.
Translated with www.DeepL.com/Translator (free version)
=> For fine control of volume and panning.

OpenUtau.Core/Editing/NoteBatchEdits.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.zh-CN.axaml, OpenUtau/ViewModels/PianoRollViewModel.cs
=> add an editing macro to remove tail "R" or tail "-"

OpenUtau.Core/Util/LyricsHelper.cs, OpenUtau/ViewModels/PhoneticAssistantViewModel.cs
- Add German Lyrics Helper;
- Add missing Spanish option to Phonetic Assistant view model.
=> [Phonetic Assistant] Add German Lyrics Helper + missing Spanish view model option

OpenUtau.Plugin.Builtin/EStoJAPhonemizer.cs
This fix is basically the same as the ones featured in #783, just for the Spanish-to-Japanese phonemizer.
**TODO:** Maybe write some tests?
=> [ES to JA Phonemizer] Consonant bug fixes

OpenUtau/Views/PianoRollWindow.axaml
=> Fix the scale of icon in pianoroll window

OpenUtau/App.axaml, OpenUtau/Strings/Strings.de-DE.axaml
Changes:
- Added German UI language
=> Add German UI language

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/Views/PianoRollWindow.axaml, OpenUtau/Views/PianoRollWindow.axaml.cs
Changes:
- Combined notes, lyrics and plugins into one "Batch Edits" menu
- Open the Singer window and focus on the selected Oto
Discussion:
https://discord.com/channels/551606189386104834/1134897555151519804
=> Tweaked piano roll menus

OpenUtau/ViewModels/NotesViewModel.cs, OpenUtau/Views/PianoRollWindow.axaml.cs
Merge Notes using Ctrl-U like Utau
=> Merge Notes

OpenUtau.Plugin.Builtin/GermanVCCVPhonemizer.cs
- Fixes split diphthongs, so that the second part gets treated as a consonant;
- VCC refactor;
- CC refactor;
- Some ``ValidateAlias()`` fixes regarding consonants.
=> [German VCCV Phonemizer] VCC refactor + CC refactor + ValidateAlias() fix + split diphthong fix

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/ViewModels/SearchNoteViewModel.cs, OpenUtau/Views/PianoRollWindow.axaml, OpenUtau/Views/PianoRollWindow.axaml.cs, OpenUtau/Views/SearchNoteDialog.axaml, OpenUtau/Views/SearchNoteDialog.axaml.cs
New Feature:
- Search Note
Search for notes in lyrics, select and focus.
Used in combination with the note properties, it would be possible to change specific notes at once.
A shortcut Ctrl + F is assigned, but if we do not need it, please return it to the original.
=> Add Search Note

OpenUtau.Core/Util/Preferences.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/ViewModels/PreferencesViewModel.cs, OpenUtau/Views/MainWindow.axaml.cs, OpenUtau/Views/PreferencesDialog.axaml
Adds an option to clear cache on quit in the Preferences menu. By default, it's off.
=> Add option to automatically clear cache on quit

OpenUtau.Core/Classic/Presamp.cs, OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
New features:
- Add replaces ぢ, づ, with じ, ず
- Support for "っ"
Improvement:
- When there is a phonetic hint, the lyrics are not replaced
=> [JA Presamp Phonemizer] Supports "っ", etc

OpenUtau/ViewModels/SingersViewModel.cs, OpenUtau/Views/SingersDialog.axaml
* Added alias search in the singer dialog even if the singer type is ENUNU.
* Because it was raised as a bug report.
* Changed handling of display flags for controls.
* SingersViewModel.cs
* SingersDialog.xml
* None in particular
=> Alias search is now available at ENUNU.

OpenUtau.Core/Classic/PluginRunner.cs, OpenUtau.Core/Ustx/UProject.cs, OpenUtau/ViewModels/NotesViewModel.cs, OpenUtau/Views/PasteParamDialog.axaml
=> Small bug fixes

OpenUtau/ViewModels/NotesViewModel.cs
Fixed a bug that pitch points move similarly before and after pasting when "Select and paste parameters".
=> Fix pitch paste bug

OpenUtau/ViewModels/TrackHeaderViewModel.cs
=> Sort language groups of phonemizers alphabetically

OpenUtau.Core/Classic/ClassicSinger.cs, OpenUtau.Core/Classic/VoiceBank.cs, OpenUtau.Core/Classic/VoicebankConfig.cs, OpenUtau.Core/Classic/VoicebankLoader.cs, OpenUtau.Core/Enunu/EnunuSinger.cs, OpenUtau.Core/Ustx/USinger.cs, OpenUtau.Core/Vogen/VogenSinger.cs, OpenUtau.Core/Vogen/VogenSingerLoader.cs, OpenUtau.Test/Classic/VoicebankConfigTest.cs, OpenUtau/ViewModels/NotesViewModel.cs
This will add the ability to change the portrait height in the character.yaml. Width will be relative and scaled from the original image size.
**TODO:** Add X and Y axis?
=> [character.yaml] Option to set portrait height (width will be relative)

OpenUtau/Views/PasteParamDialog.axaml
Bug fix:
Fixed list box selection changes when OK is pressed with Enter key.
=> Fix paste param dialog bug

OpenUtau/Views/SingersDialog.axaml.cs
Before this fix, OpenUtau crashes when we click "play sample" if the sample file isn't a valid audio file. After this fix, OpenUtau will just ignore it without crashing
OpenUtau won't crash if the avatar isn't a valid image file, so I think I should make this PR.
=> Fix openutau crashing when the sample isn't a valid audio file

OpenUtau/Views/EditSubbanksDialog.axaml.cs
Fixed stream text encoding to conform to voice bank setting.
=> Fix import/export prefixmap

OpenUtau.Core/Classic/ResamplerItem.cs
'Fixed classic pitch #862' has a issue,noncontinuous pitch when changing tempo.
This pull request fixes it.
Improvements:
* 5ticks from beginning of the score => 5ticks based with phone.adjustedTempo
=> fixed:classic pitch when changing tempo

OpenUtau.Core/Classic/ResamplerItem.cs, OpenUtau.Core/Util/TimeAxis.cs
changes the classic pitch algorithm to calculate pitch using the position of pitch samples and lerping instead of doing index math
this change simplifies the classic pitch code and improves pitch timing with tempo changes
=> improve classic pitch algorithm

OpenUtau.Core/Classic/Ust.cs, OpenUtau.Core/Classic/UstNote.cs, OpenUtau.Test/Classic/UstTest.cs
Bug fix:
Fixed pitch parsing in UstNote.cs when pitch bend is partially changed by legacy plugins (time axis only, pitch only, etc.)
=> Fix parse pitchbend from plugins

OpenUtau.Core/Classic/ClassicRenderer.cs, OpenUtau.Core/Classic/WorldlineRenderer.cs, OpenUtau.Core/Enunu/EnunuRenderer.cs, OpenUtau.Core/Render/IRenderer.cs, OpenUtau.Core/Render/RenderEngine.cs, OpenUtau.Core/Vogen/VogenRenderer.cs
Displays the currently rendering track No. in the progress bar.
=> Display track No. currently rendering

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml
Japanese:
- Updated translations
English:
- Adjusted appearance
- Delete unnecessary code (dialogs.key.caption)
↓
=> Update Japanese translation, English appearance

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/Views/MessageBox.axaml.cs
This PR makes it easier for users to report errors.
=> Copy error to clipboard

OpenUtau/Styles/Styles.axaml
=> Fix underlines are not displayed in Button

OpenUtau.Core/Commands/Notifications.cs, OpenUtau/Controls/NotePropertiesControl.axaml, OpenUtau/Controls/NotePropertiesControl.axaml.cs, OpenUtau/Controls/NotePropertyExpression.axaml, OpenUtau/Controls/NotePropertyExpression.axaml.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/ViewModels/NoteDefaultsViewModel.cs, OpenUtau/ViewModels/NotePropertiesViewModel.cs
Improvements:
- Sliders can be reset by right clicking
- Update text box when lost focus instead of immediately
- "WORK IN PROGRESS" has been removed as the required functions are now available.
Bug fix:
- Reflects portamento and vibrato presets edited by note defaults
- Reflects changes in project expression
=> Fix note property panel

OpenUtau/Strings/Strings.id-ID.axaml
I'm making this PR because pyorririn is not able to access their github account.
=> Update ID Translation (by pyorririn)

OpenUtau/Controls/TrackHeader.axaml, OpenUtau/Strings/Strings.axaml
Many new users don't know what the "M" and "S" buttons in the header of tracks mean, so I add a hover tooltip here.
=> Add hover tooltips for mute/solo toggle button and track settings button

OpenUtau.Plugin.Builtin/EnXSampaPhonemizer.cs
This is a redo of #924.
----
Ignore what this originally said. I'm basically adjusting this phonemizer to work properly with #896 (which has been a lifesaver, for the record), ironically by simplifying the code.
=> [EN X-SAMPA Phonemizer] Adjustment to recent SBP subbank refactor

OpenUtau/Strings/Strings.ko-KR.axaml
- Fixed miss translated, untranslated strings.
=> Fix Korean translation

OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/ViewModels/SingersViewModel.cs, OpenUtau/Views/SingersDialog.axaml
Write the singer type in character.yaml.
This PR should be merged after #892.
=> Set SingerType in SingersWindow

OpenUtau/Strings/Strings.axaml, OpenUtau/Views/MainWindow.axaml.cs
=> Show a dialog when dropping file if the file format is unsupported, Support ".midi" as an equivalent of ".mid" on dragging and dropping.

OpenUtau.Core/Analysis/Some.cs, OpenUtau/Views/MainWindow.axaml.cs
Bug fix:
- Fixed a bug that failed to catch exceptions that occurred during audio transcribe task.
- Able to determine if the exception is due to SOME uninstallation.
=> Fix exception catching in audio transcribe

OpenUtau/FilePicker.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Views/MainWindow.axaml, OpenUtau/Views/MainWindow.axaml.cs
=> Add a "Install Dependency (.oudep)" item in Tools menu

OpenUtau.Core/Classic/VoicebankErrorChecker.cs
Windows path is case insensitive, while MacOS path and Linux path are case sensitive. If the wave filename in oto.ini isn't the same as the filename in the file system, the voicebank still works on windows but won't work on another OS. After this PR, it will be checked in singer error report.
=> Check file name case on windows

OpenUtau.Plugin.Builtin/SyllableBasedPhonemizer.cs
Allowing prefix/suffix assignment behavior to be customized by individual phonemizers
=> Refactor affix assignment as protected virtual method

.github/workflows/pr-test.yml
Recently, appveyor randomly fails to run unit tests. This PR adds a GitHub Action to run unit tests.
=> Add a github action to run unit tests for each PR

OpenUtau.Core/Classic/VoicebankLoader.cs
~~This is all for the time being, please.~~
- ~~Fixed CheckWavExist does not fail even if Oto's wav is null~~
- Modified to reload with UTF-8 when the first line is "#Charaset:UTF-8".
=> Fix #Charaset

OpenUtau.Core/DiffSinger/DiffSingerPitch.cs, OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs, OpenUtau.Core/DiffSinger/DiffSingerSinger.cs, OpenUtau.Core/DiffSinger/DiffSingerVariance.cs, OpenUtau.Core/DiffSinger/DiffSingerVocoder.cs, OpenUtau.Core/Render/RenderEngine.cs, OpenUtau.Core/SingerManager.cs, OpenUtau.Core/Ustx/USinger.cs
After this change, openutau will remember the singers used for rendering, and free memory for DiffSinger singers that are no longer in use.
=> DiffSinger: Free memory for singers no longer in use

OpenUtau.Core/Commands/Notifications.cs, OpenUtau/ViewModels/SingersViewModel.cs, OpenUtau/Views/MainWindow.axaml.cs, OpenUtau/Views/PianoRollWindow.axaml.cs, OpenUtau/Views/SingersDialog.axaml.cs
Fixed singer window being shown in the back when opened from the main window menu.
=> Fix singer window goes behind the main window

OpenUtau.Core/DiffSinger/DiffSingerItalianPhonemizer.cs, OpenUtau.Core/DiffSinger/DiffSingerSpanishPhonemizer.cs
Add Spanish G2p Phonemizer for DiffSinger, looks for "dsdict-es.yaml".
Add Italian G2p Phonemizer for DiffSinger, looks for "dsdict-it.yaml".
=> Add Spanish and Italian Phonemizers for DiffSinger

OpenUtau.Core/Classic/VoicebankLoader.cs, OpenUtau.Core/Ustx/USinger.cs, OpenUtau/ViewModels/MenuItemViewModel.cs, OpenUtau/ViewModels/SingersViewModel.cs, OpenUtau/Views/SingersDialog.axaml
=> Show the current selection when setting encoding, singer type and default phonemizer

OpenUtau.Core/Util/Preferences.cs, OpenUtau/FilePicker.cs, OpenUtau/Views/MainWindow.axaml.cs, OpenUtau/Views/PreferencesDialog.axaml.cs
Separately memorize the most recently opened folder for the singer and that for the project.
=> Save recent open singer/project directory

OpenUtau.Core/Editing/NoteBatchEdits.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/Views/PianoRollWindow.axaml.cs
Especially useful when AI singers.
=> Add batch edit "Add breath"

OpenUtau/Strings/Strings.axaml
A recent change caused OpenUtau to refuse to open, this pull request removes this change.
=> Fix the string duplicate issue

OpenUtau.Core/Api/Phonemizer.cs, OpenUtau.Core/Ustx/UPart.cs, OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
This change does not affect other phonemizers.
~~It may not be compatible with existing ustx that use this Phonemizer.~~
Summary:
- Phonemizer may or may not specify a phoneme index
- ~~It is possible that there is no phoneme with index 0~~
- It can be used like this: [- s][さ]
=> Support "- C" in JA VCV&CVVC Phonemizer

OpenUtau.Core/DiffSinger/DiffSingerBasePhonemizer.cs
Before this change, diffsinger phonemizers return SP if lyric isn't found in the dictionary. Returning `error` will make the mistake of lyric more noticeable by the user.
=> DiffSinger phonemizers: Return error if lyric isn't found in the dictionary

OpenUtau/ViewModels/TrackHeaderViewModel.cs
There shouldn't be 2 SOLO tracks.
=> Clear solo flag on copied tracks

OpenUtau/Controls/NotePropertiesControl.axaml, OpenUtau/Controls/NotePropertiesControl.axaml.cs, OpenUtau/Controls/NotePropertyExpression.axaml, OpenUtau/Controls/NotePropertyExpression.axaml.cs
Fixed behavior when clicking on slider line.
=> Fix NoteProperiesPanel bug

OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
Adds new VCV behavior, changes vcExceptions and changes VV behavior. The output of the Phonemizer should now require less editing.
=> Eng VCCV Updates and Fixes

OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
A small issue occurred when a [CC] didn't show up when expected, this fixes it.
=> Small bug fix for last VCCV merge 

OpenUtau/ViewModels/PianoRollViewModel.cs, OpenUtau/Views/MainWindow.axaml, OpenUtau/Views/MainWindow.axaml.cs, OpenUtau/Views/PianoRollWindow.axaml
Most file editors have "Edit" menu (including windows notepad, word, photoshop), so OpenUtau should have one.
=> Add "Edit" menu to menu bar of main window and piano roll window (Undo, Redo, etc.)

OpenUtau/Strings/Strings.ko-KR.axaml
- Added translations, Improved readability.
=> Update Korean translation

OpenUtau.Core/Util/Base64.cs, OpenUtau.Core/Voicevox/VoicevoxClient.cs, OpenUtau.Core/Voicevox/VoicevoxSinger.cs, OpenUtau.Core/Voicevox/VoicevoxUtils.cs
Fixed an error in error messages.
Fixed a case where singing voice synthesis did not work correctly.
=> Small Fix Voicevox

OpenUtau.Core/Classic/Frq.cs, OpenUtau.Core/Commands/Notifications.cs, OpenUtau.Core/PlaybackManager.cs, OpenUtau.Core/Render/RenderEngine.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/ViewModels/EditSubbanksViewModel.cs, OpenUtau/ViewModels/MainWindowViewModel.cs, OpenUtau/ViewModels/PianoRollViewModel.cs, OpenUtau/ViewModels/SingersViewModel.cs, OpenUtau/Views/EditSubbanksDialog.axaml.cs, OpenUtau/Views/MainWindow.axaml.cs, OpenUtau/Views/MessageBox.axaml, OpenUtau/Views/MessageBox.axaml.cs, OpenUtau/Views/PianoRollWindow.axaml.cs
Expander is closed by default.
=> Translate error messages and put them in the expander

OpenUtau/Program.cs
=> Fix font query result with multiple comma-separated values

OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
Fixes a tiny mistake in the error message.
=> [DiffSinger] Fix error message on `mel_scale`

OpenUtau.Plugin.Builtin/EnXSampaPhonemizer.cs
Adds fallbacks for [VI] and [VU] to [aI] and [aU] in the English X-Sampa Phonemizer
=> Fallbacks for Canadian Raising in English X-Sampa Phonemizer

OpenUtau.Core/Commands/Notifications.cs, OpenUtau.Core/PlaybackManager.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/ViewModels/NotesViewModel.cs, OpenUtau/ViewModels/PianoRollViewModel.cs, OpenUtau/ViewModels/PlaybackViewModel.cs, OpenUtau/ViewModels/TracksViewModel.cs, OpenUtau/Views/PianoRollWindow.axaml, OpenUtau/Views/PianoRollWindow.axaml.cs, OpenUtau/Views/PreferencesDialog.axaml
As usual, please let me know if my English is not correct.
=> Add option to move only the cursor and not scroll back when pausing playback

OpenUtau.Core/Classic/ClassicRenderer.cs
When rendering fails, error messages display the position.
=> Showing positions that failed to render

OpenUtau.Core/DocManager.cs
When ustx have not yet been saved, save a backup in the Backup folder.
=> Auto save even when ustx is not saved

OpenUtau/ViewModels/SingerSetupViewModel.cs
https://bowlroll.net/file/231950
This is the singer that fails to unzip (unrar), and I could not find out why it fails.
=> Fixed crash when unzipping singer fails

OpenUtau/Controls/TrackHeader.axaml, OpenUtau/Strings/Strings.axaml, OpenUtau/Strings/Strings.ja-JP.axaml, OpenUtau/ViewModels/SingersViewModel.cs, OpenUtau/ViewModels/TrackHeaderViewModel.cs
New Features:
- Add "Open singers location" menu
- Add "Open additional singers location" menu
- Add "Refresh" menu
Related Fix:
- Fixed double try-catch (SingersViewModel.cs)
=> Add "Open singers location" menu

OpenUtau/ViewModels/MenuItemViewModel.cs, OpenUtau/Views/PianoRollWindow.axaml, OpenUtau/Views/PianoRollWindow.axaml.cs
=> Show InputGesture on notes context menu

OpenUtau.Core/Format/USTx.cs, OpenUtau.Core/Ustx/UTrack.cs
- Fixed ustx not saving when there is a track with an unselected singer.
- Fixed to show an error when ustx could not be saved.
=> [Important] Fix unable to save

OpenUtau/Strings/Strings.ko-KR.axaml
- Added and translated some missing Korean strings.
=> Updated Korean strings

OpenUtau/Views/NoteEditStates.cs
Before this fix, when using knife tool, if the split position is near to the end of the note to be splitted, the new note created will be very long
=> Fix very long note produced by knife tool

OpenUtau.nsi, OpenUtau/OpenUtau.csproj
Added .ustx file association to the Windows installer and MacOS, so opening a file will automatically open it in OpenUtau.
=> Add .ustx file association on Windows and MacOS

OpenUtau.Core/Editing/ResetBatchEdits.cs, OpenUtau/Strings/Strings.axaml, OpenUtau/Views/PianoRollWindow.axaml.cs
The editing macro is called `Reset notes to default`. Please tell me if you come up with a better name.
=> Add a 'reset all' editing macro

OpenUtau/Strings/Strings.vi-VN.axaml
- Translated untranslated strings.
- Added and translated missing strings.
- Attempted at localizing oto terminology instead of keeping them in English. (please provide feedback on whether to keep this change)
=> Updated Vietnamese translation

OpenUtau/Strings/Strings.de-DE.axaml
Add and fix several German translations.
=> Update translations in Strings.de-DE.axaml

OpenUtau.Plugin.Builtin/ArpasingPlusPhonemizer.cs
Re-adjusted consonant lengths for liquids, semi-vowels, and long consonants
=> [ARPA+ Phonemizer] Re-adjusted consonant lengths

OpenUtau.Core/G2p/ArpabetPlusG2p.cs
update dictionary (fixes incorrect pronunciation of certain words + added new data)
=> Update ARPA+ G2p Dictionary (preparing for model retrain)

OpenUtau.Plugin.Builtin/ArpasingPlusPhonemizer.cs
fixed ending timings to 0.5 ms
=> [EN ARPA+] Fix ending vowel and consonant timings

OpenUtau.Core/Classic/ExeResampler.cs
Many users encountered "Unsupported file type" issue when rendering using moresampler with wrong moreconfig. After this change, OpenUtau will check moreconfig.txt and fix it when launching.
=> Check and patch moreconfig.txt when launching

OpenUtau.Core/BaseChinesePhonemizer.cs, OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerJyutpingPhonemizer.cs, OpenUtau.Core/OpenUtau.Core.csproj, OpenUtau.Core/Util/LyricsHelper.cs, OpenUtau.Plugin.Builtin/CantoneseCVVCPhonemizer.cs, OpenUtau.Plugin.Builtin/CantoneseSyoPhonemizer.cs
G2P migration to [csharp-pinyin](https://github.com/wolfgitpr/csharp-pinyin).
=> update chinese g2p

OpenUtau.Core/Ustx/USinger.cs, OpenUtau/ViewModels/LyricBoxViewModel.cs
A similar bug to #1220 but in lyric box
=> Fix openutau crashing after pressing Ctrl+Z in lyric box twice and enter

OpenUtau/Controls/LyricBox.axaml, OpenUtau/ViewModels/LyricBoxViewModel.cs
Fixed duplication of alias and folder paths when folders are deep.
↓
=> Fix LyricBox UI

OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
Fix error on works containing "skt" eg, `Desktop`
=> [EN VCCV] Missed exception for "skt"

OpenUtau.Core/Editing/ResetBatchEdits.cs, OpenUtau/Views/PianoRollWindow.axaml.cs
=> When resetting expressions, only reset curve expressions where the note is selected; Remove duplicate editing macros

OpenUtau.Core/KoreanPhonemizerUtil.cs, OpenUtau.Plugin.Builtin/BaseKoreanPhonemizer.cs, OpenUtau.Plugin.Builtin/KoreanCVCCVPhonemizer.cs, OpenUtau.Plugin.Builtin/KoreanCVCPhonemizer.cs, OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
I added Romanized lyrics mapping to the Korean phonemizer.
=> Add Romanized lyrics support to all Korean phonemizers

OpenUtau/Views/NoteEditStates.cs
Incorrect method of determining curves has been corrected.
=> Fix ExpEdit

OpenUtau/Controls/LyricBox.axaml.cs
Fixed problem with mouse clicks not responding.
=> Fix LyricBox

OpenUtau/Strings/Strings.de-DE.axaml
Translations for some of the newer tools and other fixes.
=> Update German translation

OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
A pitch model with `use_note_rest: false` can bypass the phoneme definition checks unexpectedly. After this PR, dspitch will always check if each phone has type definition in dsdict.yaml.
> Background: 
> The pitch predictor requires midi value interpolation on rest notes, and whether a note is rest depends on the types of its phones. So this is to prevent unexpected interpolation due to missing phoneme type definitions.
=> Remove conditions on phoneme definition checks of dspitch

OpenUtau/Strings/Strings.axaml, OpenUtau/ViewModels/TrackHeaderViewModel.cs
=> show singer default phonemizer in track phonemizer menu

OpenUtau/Views/SplashWindow.axaml, OpenUtau/Views/SplashWindow.axaml.cs
I have fixed the splash window as it was misaligned in my windows environment, but have not tested it on Mac or Linux, so any feedback would be appreciated.
=> Centering the Splash Window

OpenUtau.Core/Commands/ExpCommands.cs, OpenUtau.Core/Editing/NoteBatchEdits.cs, OpenUtau/ViewModels/NotePropertiesViewModel.cs
Processing has been sped up by combining multiple phoneme edits into a single command.
This has greatly improved the response of the Note Properties panel.
=> Faster expression commands

OpenUtau.Core/Classic/ExeWavtool.cs
This fixes the issue with external wavtools to avoid command exploits https://github.com/stakira/OpenUtau/issues/1402
=> Fix Command Injection Vulnerability in Classic Renderer

OpenUtau.Plugin.Builtin/Data/en_cPv.template.yaml, OpenUtau.Plugin.Builtin/EnglishCpVPhonemizer.cs
Delete `en-cPv.yaml` once this update merges to apply the dictionary update
=> [EN C+V] Code fixes and Dictionary updates

OpenUtau.Plugin.Builtin/ArpasingPlusPhonemizer.cs
I thought I've fixed this before 🤔
=> [EN ARPA+] Fixes vanila Arpabet phonemes conflicts to Romaji VV

OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
Changes Starlight Fix code to fix issues with [l l], [n n] and [m m].
=> Update Starlight fix

OpenUtau.Core/Classic/VoicebankLoader.cs
=> Fix "#Charset:"

OpenUtau/Strings/Strings.axaml
The `tip.exps` string has been changed to include more detailed descriptions of the number and option types. New operations include operations using the left and right buttons, Ctrl and Shift. New operations on curve types have also been added to help users understand more operating options.
=> Updated operating instructions.

OpenUtau/Views/PianoRollWindow.axaml.cs
This will make it faster and more convenient to generate new pitch takes by selecting notes on Piano Roll
=> Ctrl+R for Load rendered pitch

OpenUtau/Views/MainWindow.axaml
Fixed drag-and-drop problem on some parts of the welcome page and main page
=> Fix drag and drop area in main window

OpenUtau/Views/PianoRollWindow.axaml.cs
=> Fix batch edit order

OpenUtau.Core/Classic/ClassicSinger.cs, OpenUtau.Core/Classic/Frq.cs, OpenUtau.Core/Render/RenderPhrase.cs, OpenUtau.Core/Ustx/USinger.cs
=> Revert "MOD+ related bug fixes"

OpenUtau.Core/Classic/ClassicSinger.cs, OpenUtau.Core/Classic/Frq.cs, OpenUtau.Core/Render/RenderPhrase.cs, OpenUtau.Core/Ustx/USinger.cs
This is a modification of #1566.
=> (Re) MOD+ related bug fixes
