- OpenUtau/Core/USTx/UTrack.cs
- OpenUtau/UI/MainWindow.xaml.cs
1. Fix the bug that causes the application to crash when canceling the "Import Midi..." OpenFileDialog.
2. Fix a typo in `UTrack.cs`.
> Bug Fix and Typo Fix

- OpenUtau/Classic/VoicebankInstaller.cs
Some Utau singers, such as the ones at [this site](https://marginalsynth.wixsite.com/utau/) use ": " as a delimiter in their character.txt files rather than "=". For this reason, singers from that site (and potentially other sites) fail to import due to character.txt parsing issues. 
To fix this, I made OpenUtau fall back on attempting to parse using a ": " delimiter if "=" does not work. Now singers from that site load without issue.
I also made it read the "created by" key in character.txt, and set the author information based on that. Now character.txt files that have a "created by" key but no "author" key can still have their author information loaded.
I have successfully tested my changes with [this singer](https://marginalsynth.wixsite.com/utau/sayuri).
> Singer character.txt parsing fixes

- OpenUtau/Core/Formats/Ust.cs
Invalid Envelope
"E:\Documents\Synths\UST\CVC RUS USTs\представь на мне корону (you should see me in a crown) [Billie Eilish]\p1.ust"
at line 25:
"Envelope=30,0,0,100,100,100,100,%,50,0,100"
Pitch problem note (idk why there are 3 extra shapes, probably utau doesn't delete points correcly):
[#0050]
Length=1387
Lyric=t'i
NoteNum=63
PreUtterance=
Intensity=100
Modulation=0
PBType=5
PitchBend=-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-199,-195,-191,-184,-177,-168,-157,-146,-134,-122,-109,-96,-83,-70,-58,-46,-36,-26,-18,-11,-6,-2,0,0
Envelope=30,575,200,100,100,53,0,%,0,213,72
PBM=,,s,s,
PBS=0
PBW=100
PBStart=-103
> crash on long envelope & utau pitch extra points

- OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
Removed the gap when the following note wasn't recognized
> Fix behavior of JA CVVC phonemizer with unrecognized notes

- OpenUtau.Core/Classic/VoicebankLoader.cs
[00:44:16 ERR] Failed to parse
"H:\Program Files (x86)\UTAU\voice\Blue Trey CVC\oto.ini"
at line 2:
"濵濵・wav=,,,,,"
System.ArgumentException: String cannot be of zero length. (Parameter 'oldValue')
at System.String.Replace(String oldValue, String newValue)
at OpenUtau.Classic.VoicebankLoader.ParseOto(String line) in H:\External\Github\HeidenBZR\OpenUtau\OpenUtau.Core\Classic\VoicebankLoader.cs:line 318
at OpenUtau.Classic.VoicebankLoader.ParseOtoSet(Stream stream, String filePath, Encoding encoding) in H:\External\Github\HeidenBZR\OpenUtau\OpenUtau.Core\Classic\VoicebankLoader.cs:line 273
> fix crash on VoicebankLoader.ParseOto

- OpenUtau.Core/Ustx/USinger.cs
[00:59:19 ERR] Failed to load avatar data.
System.IO.FileNotFoundException: Could not find file 'H:\Program Files (x86)\UTAU\voice\Gian VCCV old\icon.bmp'.
File name: 'H:\Program Files (x86)\UTAU\voice\Gian VCCV old\icon.bmp'
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode)
at OpenUtau.Core.Ustx.USinger..ctor(Voicebank voicebank) in H:\External\Github\HeidenBZR\OpenUtau\OpenUtau.Core\Ustx\USinger.cs:line 155
> fix crash avarar is set but file does not exist

- OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
- fixed bugs with ㅚ and ㅢ
- added support for `kk`, `tt`, and `pp` phonetic hint for ㄲ, ㄸ, and ㅃ
- added support for `ae`, `yae`, and `wae` phonetic hint for ㅐ, ㅒ, and ㅙ
> Korean VCV Phonemizer

- OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
- batchim sounds will now be placed relative to a note's last extender instead of the first note
- _previously, batchim sounds were placed within the duration of the first note, ignoring extenders_
> KO VCV Phonemizer update

- OpenUtau.Core/Ustx/UPhoneme.cs
Fixes bug where short notes affected next preutterance even when notes were non-adjacent
> Use prevDur only when overlapped

- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.es-ES.axaml
- OpenUtau/Strings/Strings.es-MX.axaml
- OpenUtau/Strings/Strings.fi-FI.axaml
- OpenUtau/Strings/Strings.fr-FR.axaml
- OpenUtau/Strings/Strings.id-ID.axaml
- OpenUtau/Strings/Strings.it-IT.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Strings/Strings.ko-KR.axaml
- OpenUtau/Strings/Strings.nl-NL.axaml
- OpenUtau/Strings/Strings.pl-PL.axaml
- OpenUtau/Strings/Strings.pt-BR.axaml
- OpenUtau/Strings/Strings.vi-VN.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewConstants.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/ViewModels/TracksViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
This PR adds a setting in the preferences dialog to allow the user to change the position at which the playhead will be tracked during playback.
> Add setting for playhead tracking position

- OpenUtau/Resources/Resources.resx
Fix case of Unzipper.exe reference for case-sensitive platforms (eg. Linux)
> Fix case of Unzipper.exe

- OpenUtau.Plugin.Builtin/FrenchCVVCPhonemizer.cs
This is a French CVVC Phonemizer compatible with the Petit Mot reclist. It supports CVVC and CVVC+ and also has hiragana support for "cross-language". 
Many utaus (the Fraloids and other utaus in the community) are being converted to fit the phonemizer.
> French CVVC Phonemizer

- OpenUtau.Core/Classic/VoicebankFiles.cs
RUCE is an old UTAU engine, a part of Rocaloid project (now discontinued). It uses its own intermediate sound model file with *.rudb extension. Adding rudb files to meta file list, and then RUCE will work in OpenUTAU.
> Add .rudb to meta file list to support an old engine RUCE

- OpenUtau.Core/PlaybackManager.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/PlaybackViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
Closes #114
---
One thing to notice is that `PlaybackManager` is at present not good at seeking to a new position. User experience would be better if the `Task` or the `RenderEngine` created in `PlaybackManager.Render` could be reused after seeking. I'll create a seperate issue later to track this.
> Add an option to move back cursor on pausing

- OpenUtau.Plugin.Builtin/TetoEnglishPhonemizer.cs
Teto English lacks the `bVbVb` sample and all associated OTO entries, so it's replaced with the corresponding phonemes from `b@b@b`.
> Use b@ instead of bV

- OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs
* Consonant transition issues got fixed.
* Now supports VCV with more than one consonant if the voicebank has it.
* Supports "consonant VCV", e.g. [n da], [l ba] etc. if the voicebank has it.
* Consonant length adjustment.
* "ny" is now a fallback for "nh" if the voicebank doesn't have the latter (CVVC-only).
* Use seseo ("s" instead of "z") when a voicebank doesn't have "z" (might be CVVC-only).
**TODO:**
* Make VCV with "ny" work automatically as a substitute for "nh" if the voicebank has it, instead of always going for CVVC.
* Make ValidateAlias for using "i" instead of "y" and "u" instead of "w" work properly if the voicebank has them.
> [Spanish Phonemizer] Fixed transition issues & added new functions

- OpenUtau.Core/Commands/ExpCommands.cs
- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau.Core/Format/Midi.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau.Core/Ustx/UProject.cs
- OpenUtau.Core/Util/NotePresets.cs
- OpenUtau.Core/Util/PathManager.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/NoteDefaultsViewModel.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/PianoRollViewModel.cs
- OpenUtau/Views/NoteDefaultsDialog.axaml
- OpenUtau/Views/NoteDefaultsDialog.axaml.cs
- OpenUtau/Views/NoteEditStates.cs
- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
Added a window for default notes settings - lyric, portamento and vibrato.
- Portamento settings include start and length;
- Vibrato settings include length, period, depth, fade in and out, and shift, as well as toggle for automatic vibrato and minimum note duration for adding it;
- Portamento and vibrato have presets, which user can add or remove;
- Default settings and presets are saved in a file separate from preferences;
- Batch edit previously named "Reset vibratos" is now named "Clear vibratos" and current "Reset..." applies all the default values;
Small bug which I wasn't able to fix: preset dropdown lists don't update after adding or removing presets, the window needs to be reopened for changes to be seen.
> Add note defaults & presets

- docs/index.md
Links previously went to openutau.com/`LinkName` because of it being set up like `.LinkName` for the link.
> Fix links on index.md

- OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
This is a temporary workaround for the lack of phonemizer for Cz's VCCV method. Since it uses an arpabet dictionary, it lacks some vowels right now but it is fully working. _Known issues:_
- There may be some more VC exceptions to add. 
- The phonemizer defaults to [V C] for parsing, maybe it should be [VC-]. Feedback welcome, please test it yourself! 
- CC conflicts with "zh/z+h" "th/t+h" etc.
**TODO:** 
- Make VC exceptions cleaner and sturdier (maybe use GetSymbols())
- Work out a solution for additional vowels and sounds (dd, h/hh)
Feel free to contribute. :) 
The Lyric Parser plugin is still a sturdier alternative.
> EN VCCV (Cz's) Phonemizer 

- OpenUtau.Plugin.Builtin/ENtoJAPhonemizer.cs
- OpenUtau.Plugin.Builtin/EStoJAPhonemizer.cs
- OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs
The Spanish to Japanese Phonemizer is mostly based on the English to Japanese Phonemizer, code-wise; just with some tweaks specific to Spanish. But it functions more or less the same way.
Will add info to the wiki as soon as it's merged.
I also noticed that the ENtoJA Phonemizer didn't have support for vowel endings, so I added it.
I also tweaked the ES-SYL phonemizer a bit, shouldn't be too different in terms of functionality though. No new functions have been added for now.
> Added "Spanish to Japanese Phonemizer" + vowel ending support for ENtoJA Phonemizer + ES-SYL Phonemizer simplifications

- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/DebugViewModel.cs
- OpenUtau/Views/DebugWindow.axaml
Added reverse log order to preferences (`SerializablePreferences`)
Added reverse log order string (`Strings`, English only (let me know and I can add it to other language files too))
Added reverse log order functionality and sorted usings (`DebugViewModel`)
Added reverse log order button and command binding (`DebugWindow`)
> add reverse log order button

- OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
Quick fix for a bug where CV vowels wouldn't be accounted for with the JP CVVC phonemizer.
> Allow CV vowels for JP CVVC phonemizer

- OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
- OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
These phonemizers are supposed to work with any Delta list-based English banks, including Kasane Teto.
The main difference between the two is that the first version is for "full" diphthongs, while the second is for "split" diphthongs (e.g. "light" is [l aI t] in the first, [l a I t] in the second).
They should work alright, I didn't find any significant bugs while testing the current code. Please let me know if there are any errors, mistakes, bugs, etc.
> [EN Delta] Added general Delta English phonemizers (2 versions) [BETA-ISH]

- OpenUtau.Core/Format/Midi.cs
- OpenUtau.Core/OpenUtau.Core.csproj
不同软件导出的Midi文件歌词编码不同，因此使用[Nchardet](https://github.com/thinksea/NChardet)库（[开源协议](https://github.com/thinksea/NChardet/blob/master/LICENSE)）进行自动检测。
若不允许引用该库，可以合并我的[midi-lyric](https://github.com/oxygen-dioxide/OpenUtau/tree/midi-lyric)分支，该分支仅支持导入ascii编码的歌词
> midi导入：支持歌词 / Midi importing: lyric support 

- OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
Please note that it will inherit the main voice color's ``[- CV]``, ``[V V]`` and/or ``[V C]`` notes if the voice color of your choice does not contain them but the main color does. However, there should be no issue with CV banks, as well as CVVC banks with a consistent aliasing system across all voice colors.
I've also added support for crossfade vowels (``[* V]``) if the voicebank has them. The above also applies here.
> [JP CVVC Phonemizer] CV voice color fix + add crossfade vowel support

- OpenUtau/OpenUtau.csproj
The latest stable version of Avalonia UI includes additional input features (including the KeyGesture class) I'd like to use in further PRs. I didn't see any breaking changes in my review, but I'm only testing in Windows.
> Bump AvaloniaUI to 0.10.18

- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Controls/NotesCanvas.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
This PR adds a "Ghost Notes" feature to OpenUtau, that shows the notes of other tracks when viewing a part in the Piano Roll. This is similar to the "Ghost Notes" feature in FL Studio, or Ableton's multi-clip view.
* Added preferences option for enabling/disabling feature
* Handles part changes/moves
[ ] Review naming / language - I'm not married to "Ghost Notes"
[ ] Review styling choices (currently uses existing "NeutralAccentBrushSemi" brush color, and display slightly thinner)
[ ] Add additional translation strings
[ ] Choose default option (enabled/disabled)
[ ] Handle initial load when preference not set *(I'm not familiar with this behavior)*
> Add ghost notes feature (show notes in other tracks in piano roll)

- OpenUtau.Core/Enunu/EnunuEnglishPhonemizer.cs
Sometimes consonant will occupy the full length of a note
Before fix:
After fix:
> enunu english: fix a bug

- OpenUtau.Plugin.Builtin/KoreanCVCPhonemizer.cs
- Pitch symbols now work again.
- Voice color support added.
- End breath support added (in Korean CVC, this is done by adding a tail ``R`` note).
- Code cleanup (similar to JA CVVC phonemizer).
**TODO (for future PRs):**
- Plain vowel fix?
- "L" fix?
- Fix the other phonemizers similarly, so that they'll support pitch symbols and voice colors again. **Help is wanted, feel free to contribute if you're able. This will be a lot of work.**
> [KO CVC Phonemizer] Pitch symbol fix, added end breath + voice color support, code cleanup

- OpenUtau/Views/PianoRollWindow.axaml
Before fix:
After fix:
I'm using Windows. I'm not sure know how it looks on other platforms.
> fix pen plus tool icon's color in dark mode

- OpenUtau.Plugin.Builtin/ChineseCVVPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVCCVPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVVCStandardPronunciationPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
- OpenUtau.Plugin.Builtin/VietnameseCVVCPhonemizer.cs
- OpenUtau.Plugin.Builtin/VietnameseVCVPhonemizer.cs
This restores pitch symbol support in certain legacy phonemizers, and in certain cases, voice color as well.
Affected phonemizers:
- ZH CVV
- KO CVCCV
- KO CVVC
- KO VCV (also restores voice color)
- VIE CVVC (also restores voice color)
- VIE VCV (also restores voice color)
I might replace legacy mapping in these phonemizers one day with a better solution, similar to KO CVC (which uses a different, non-legacy mapping method).
Phonemizers not listed weren't affected, so no action needed to be taken there.
> [Multiple phonemizers] Add legacy mapping support

- OpenUtau.Core/Classic/Plugin.cs
- OpenUtau.Core/Classic/PluginLoader.cs
- OpenUtau.Core/Classic/Ust.cs
- OpenUtau/ViewModels/PianoRollViewModel.cs
In non-Japanese OS, we will see paths that can't be encoded to shift_jis sometimes. This patch add an "encoding" option that enables classic plugins to use a different encoding for their temp files, such as UTF-8.
(left: shift-jis, right: UTF-8)
plugin.txt example:
```
name=OpenUTAU Pack Tool
execute=main.bat
shell=use
encoding=utf-8
```
notes:
* plugin.txt still have to be shift_jis
* The default encoding of temp files is still shift_jis
> enable classic plugins to use encodings other than shift_jis / 允许UTAU插件使用非shift_jis编码

- OpenUtau/Program.cs
When running in debug mode in VS for mac, the process name uses `dotnet`, which could be used already, and thus the program exits.
This PR is just for your information as an example of the solution. It works in my case, but I am not sure if it's complete.
> Skip process name check when debugging in VS for mac

- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
- Implement note multi-selection toggle by `Control + Click`:
- If the clicked note is not selected, select it
- If the clicked note is already selected, deselect it
- Implement note range multi-selection by `Shift + Click`:
- If the clicked note is not in the range of currently selected notes (the range means the first selected ~ the last selected), select the all the notes in the range [clicked, last] or [first, clicked]
- If the clicked note is in the currently selected range, select all the notes in the range
https://user-images.githubusercontent.com/7665216/193639591-364a3224-5e16-43b8-aa19-3715f3dbb254.mp4
https://user-images.githubusercontent.com/7665216/193639625-b67d9605-bb67-4133-9f37-793781fef3a4.mp4
> Implement note multi-selection by `Ctrl + Click` and `Shift + Click`

- OpenUtau.Plugin.Builtin/Data/envccv.template.yaml
Added a few lines I had initially assumed wouldn't work after testing more thoroughly. Added 2 CZsampa consonants that couldn't be manually input if the user was only familiar with CZsampa and/or were importing a dictionary formatted as such.
> envccv dict template fixes

- OpenUtau.Core/Util/OS.cs
- OpenUtau/Integrations/VLabelerClient.cs
- OpenUtau/Views/PreferencesDialog.axaml.cs
- OpenUtau/Views/SingersDialog.axaml.cs
1. Fix the app path
2. Add delay between heartbeat tries
3. Make request timeout longer
When running `vLabeler production` and `OpenUtau` in VS,
If once started `vLabeler` by `OpenUtau`, the `dotnet` process cannot be correctly closed (even if `vLabeler` has already been closed).
May need some cleanup for the started process?
> Fix vLabeler integration for macOS

- OpenUtau/Integrations/VLabelerClient.cs
vLabeler is now supporting folders like `aaa/bbb` but the separator is always `/`, so we need to replace `\` on Windows with `/` to make it work.
> Replace "\" with "/" in the oto set name when sending request to vLabeler

- OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
- OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
- Bug fixed where in certain cases, a fallback vowel would be used instead of the default.
- Bug fixed where there would be no burst consonant added with certain CC and VCC transitions.
- Slight VCC code optimization.
All applies to both phonemizers.
> [EN Delta Phonemizers] Fixed vowel fallback, CC and VCC bugs

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/MainWindow.axaml.cs
Implemented Replace audio in the context menu of UWavePart in the parts editor. This can be useful when i.e. sending project to others, moving to a new computer, etc.
Known issue need help: When undoing this action, without a seek action, the original audio will still play.
> Implemented Replace audio for UWavePart

- OpenUtau.Core/Commands/NoteCommands.cs
- OpenUtau/ViewModels/NoteSelectionViewModel.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/Views/LyricsDialog.axaml
- OpenUtau/Views/LyricsDialog.axaml.cs
- OpenUtau/Views/NoteEditStates.cs
- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
This PR addresses #386 and adds a number of additional keyboard shortcuts to the piano roll view. This is a fairly big PR so I tried to break the changes into smaller commits to *(hopefully)* make reviewing easier. 
* navigate through notes using Left+Right. Scrolls view as necessary.
* move/resize notes
* enter key opens Lyric Dialog instead of Lyric Box if multiple notes selected (dialog is not accessible and listens for Enter/Esc)
* playback position control
* view scroll/zoom
* add new note with insert key
* **my favorite** - Set playback position to current note with `Ctrl+F`, great when combined with Left+Right to quickly review a phrase
* Lyric Dialog no longer accepts Tab/Enter keys (I don't see the use case for using them. You can still paste in text with these characters). It …
> Piano Roll keyboard control

- OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
- OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVCPhonemizer.cs
KR CVC:
This fixes an end breath issue on Romanized notes containing "eo" or "eu", similar to #530.
--
EN Delta:
- Burst consonants overhaul/removal; this function has now been made exclusive to affricates. This was done due to how English pronunciation is affected in singing.
- Applied consonant length differences (short + long + normal).
> [Korean CVC Phonemizer + English Delta Phonemizers] KR end breath bug fix for "eo", "eu" + EN consonants overhaul

- OpenUtau.Core/Classic/ClassicRenderer.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
Added new "Maximum Render Threads" slider to preferences. 
Max threads are determined by number of logical processors (cores/simultaneous threads) of the system CPU. 
Setting only affects classic resamplers using internal wavtools (convergence, simple).
> Restore render thread option

- OpenUtau.Plugin.Builtin/FrenchCVVCPhonemizer.cs
- OpenUtau.Plugin.Builtin/FrenchVCCVPhonemizer.cs
Added japanese 4 & h support for French dictionary for both phonemizers
Changed behaviour of VCCV phonemizer:
- No longer tries to add hard "- C" (t, d, p, k, d)
- Can now add "V V" in the same note with phonetic hint
- Added vocal fry consonants to consonant list for easier phonetic input
Fixed behaviour of CVVC phonemizer:
- Removed unnecessary sounds during CC transitions
- Fixed missing CCs at the end
> Improved behaviour and multilingual support for French phonemizers

- OpenUtau.Core/Commands/ExpCommands.cs
Changes in VEL are now applied to PhonemeAttributes.consonantStretchRatio
> Phonemizers see changes in VEL

- OpenUtau.Core/OpenUtau.Core.csproj
- OpenUtau.Core/Util/Yaml.cs
- OpenUtau.Test/Classic/VoicebankConfigTest.cs
- OpenUtau.Test/Core/USTx/UstxYamlTest.cs
The English word "null" cannot be used in lyrics when saved as a USTX file. The YAML parser reads a literal null on load and fails. [Discord bug report](https://discord.com/channels/551606189386104834/801525671775043625/1054981543170428928)
* `.WithQuotingNecessaryStrings()` is used in yaml serializer to force quote "null", "true", "false" and numbers strings
* ~Updating YamlDotNet to 12.0.0~ 
* Updating YamlDotNet to 12.0.1, 
* `.WithQuotingNecessaryStrings()` is only supported in YamlDotNet version 12.0.0 and above. See https://github.com/aaubry/YamlDotNet/issues/591
* YamlDotNet version 12.0.0 has bug deserializing string "-@" and "-&". This bug is fixed in version 12.0.1. See https://github.com/aaubry/YamlDotNet/issues/719
* "null" and "true" serializing are added to test.
> Fix "null" strings on writing yaml files

- OpenUtau.Plugin.Builtin/Data/Resources.Designer.cs
- OpenUtau.Plugin.Builtin/Data/Resources.resx
- OpenUtau.Plugin.Builtin/Data/xsampa.template.yaml
- OpenUtau.Plugin.Builtin/ENDeltaVer1Phonemizer.cs
- OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVCPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
KOR VCV:
- Fixes end breaths aliased with ``bre``.
- Adds support for English "r" (aliased ``rr``).
KOR CVC:
- Optional VV support
- Make Hangul initial optional
- Support for VV and VC notes between different scripts (e,g. from Hangul to romaja & from romaja to Hangul)
- Fix romaja ``eui`` VC bug
- Added Konglish rhotic "er" vowel (only V/VV, no C+V or VC. Unless someone really wants it)
- Added optional ``ng`` connectors
- Automatic change of "r" to "l" if there's no starting CV
- **TODO (for future PR):**
- "L" bug fix
- Automatic romaja finals? (I don't know how to code that yet)
EN Delta Phonemizers:
- Added support for ``@r`` phoneme (Version 1 only)
- Added custom dictionary support (both phonemizers; associated resource templates have been created as well)
> [Multiple phonemizers] Added functions and tweaks; please read description

- OpenUtau.Plugin.Builtin/KoreanCVCCVPhonemizer.cs
- OpenUtau/Strings/Strings.ko-KR.axaml
* Responding so that it can be used even when aliases other than Hangul, which had not previously worked, are placed before and after.
* Improving the structure that was difficult to modify the aliases of the interconsonant combination
* Added korean translation
* 이전에는 동작하지 않았던 한글 이외의 앨리어스가 전후로 배치된 경우에도 모두 사용할 수 있도록 대응
* 자음간의 상호 조합을 수정하기 어렵던 문제를 수정
* 한국어 번역 추가
> fix: Korean CVCCV

- OpenUtau.Core/Enunu/EnunuConfig.cs
some enunu voicebanks don't have "extensions" attribute in their enuconfig.
> Fix enunu not rendering when there is no extensions in enuconfig / 修复enuconfig中没有插件时不渲染的bug

- OpenUtau.Core/OpenUtau.Core.csproj
- OpenUtau.Test/Core/USTx/UstxYamlTest.cs
Fixing a bug similar to https://github.com/stakira/OpenUtau/pull/576 . Input `-,` as lyric and save as an ustx file. OpenUtau will fail to load this file and says, "Invalid key indicator format".
* Updating YamlDotNet to 12.3.1
* "-," serializing and deserializing is added to test.
> fix "-," string in loading yaml files

- OpenUtau.Core/Render/RenderPhrase.cs
- Fixed #425 . Before this fix, if the user changes the default value of a curve expression, renderer will still get a null curve and the changed default value won't work. User have to draw the curve to let the default value work. 
- Renderers will be able to receive their custom curves, which can be defined with expression suggestion ( #599 )
This idea comes from diffsinger development. Recently diffsinger has implemented voice color mixing. Each voice color in the voicebank will be a curve expression. Diffsinger renderer will suggest curve expressions based on voice colors included in the voicebank.
> Fix curve default value not working, add renderer custom curve support.

- OpenUtau.Core/Classic/ClassicRenderer.cs
- OpenUtau.Core/Classic/WorldlineRenderer.cs
- OpenUtau.Core/Enunu/EnunuRenderer.cs
- OpenUtau.Core/Render/IRenderer.cs
- OpenUtau.Core/Vogen/VogenRenderer.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/ExpressionsViewModel.cs
- OpenUtau/Views/ExpressionsDialog.axaml
This is a developer-side feature for renderer developers to dynamically suggest expressions based on current singer and resampler settings. An example of this feature is implemented in CLASSIC renderer that reads expressions from a resampler manifest file located in the same folder with the resampler. 
Todos:
- ship some common resamplers' manifest files with openutau builds (editable by users and not being reseted on updates)
- support ENUNU flags (I don't know how ENUNU flag system works)
- remove resampler.exe specific flags from new project creation, because some users may never use resampler.exe
> Let renderers provide expression suggestions

- OpenUtau.Core/SingerManager.cs
- OpenUtau.Core/Util/LocalizedSort.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/ViewModels/TrackHeaderViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
After this change, users will be able to sort their voicebanks in a certain language, such as pinyin (zh-cn). This would be very convenient if the user have many voicebanks installed.
The sorting order can be different from the UI language. For example, If a Chinese user have a lot of Japanese voicebanks installed, he may want to sort his voicebanks in Japanese while seeing OpenUtau's UI in Chinese.
> String sort localization / 字符串排序本地化

- OpenUtau.Plugin.Builtin/ENDeltaVer2Phonemizer.cs
Fixes an issue regarding ``[V C]`` + ``[C -]`` fallback endings. Similar to #619.
> [EN Delta V2] Ending consonant fallback fix

- OpenUtau.Core/Util/TimeAxis.cs
- OpenUtau.Test/Core/Util/TimeAxisTest.cs
Before this fix, the actual playing speed depends not only on the tempo but also the upper number of the time signature. After this fix, the actual playing speed only depends on the tempo, ignoring time signatures in speed calculations, which is consistent with the other music editing softwares, like UTAU, deepvocal and X Studio. 
This PR fixes #521
> Time signature fix

- OpenUtau.Core/Classic/ExeWavtool.cs
- OpenUtau.Core/Classic/ResamplerItem.cs
- OpenUtau.Core/Render/RenderPhrase.cs
- OpenUtau.Core/Util/MusicMath.cs
- OpenUtau.Core/Util/TimeAxis.cs
fixes timing issues with the classic renderer with bpm changes
- note duration is now correct when changing bpm mid note
- pitches are now timed correctly when changing bpm mid note
> fix classic renderer timing with bpm changes

- OpenUtau.Core/Editing/LyricBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PianoRollViewModel.cs
Suggested in https://discord.com/channels/551606189386104834/1080759098741641267 . An lyric batch edit was added to remove all the phonetic hints from selected notes. This would be useful when I want to use an existing ustx on another VB type of the same language.
> Add a phonetic hint remover

- OpenUtau.Core/OpenUtau.Core.csproj
- OpenUtau.Core/Util/Onnx.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau.Core/Vogen/VogenRenderer.cs
- OpenUtau/OpenUtau.csproj
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
Support ONNX inferencing with directML and CoreML for vogen renderer
Note: Don't use directML or CoreML for g2p and phonemizers. They should be CPU-only. Because these runtimes may sometimes fail to work, and phonemizers can't show error dialog. CPU's performance is good enough for phonemizers.
---
添加了ONNX directML和CoreML支持，用于vogen渲染器
注意：g2p和音素器请不要使用directML和CoreML，而是仅使用CPU运行。因为directML和CoreML可能在某些情况下无法运行，而音素器不会弹窗报错。CPU的性能足够用于音素器。
> ONNX: support directML and CoreML

- OpenUtau.Core/OpenUtau.Core.csproj
on windows, only use Microsoft.ML.OnnxRuntime.DirectML. Microsoft.ML.OnnxRuntime is removed.
> ONNX DirectML: fix unable to find an entry point

- .gitignore
Visual Studio Code creates a .vscode folder when debugging, like jetbrain's .idea and visual studio's .vs folder.
> add .vscode folder into gitignore

- OpenUtau.Core/Classic/Ust.cs
- OpenUtau.Test/Classic/UstTest.cs
- Any missing values after the plugin runs will use the existing block values. 
- Because the plugin sometimes returns only some blocks.
- Value is Lyric, Position, Duration, Tone. (Where null was setting)
- Create a simple unit test.
Other values are either already supported or not supported yet.
not supported value is need to fix separately. (ex. flags)
But I think many plugins work with this fix.
> Fix disappearing notes on plugin execution

- OpenUtau.Core/Classic/IPlugin.cs
- OpenUtau.Core/Classic/Plugin.cs
- OpenUtau.Core/Classic/PluginRunner.cs
- OpenUtau.Test/Classic/PluginRunnerTest.cs
- OpenUtau/ViewModels/PianoRollViewModel.cs
- Plugin logic move from ViewModel to OpenUtau.Core.
- Create interface IPlugin.( for unit test)
- Create unit test.
This fix might makes easier for plugins test in future.
But I know we have various concept on coding.
If more good thoughts, would you give me.
> Refactor PluginRunner to OpenUtau.Core and testable

- OpenUtau.Core/Util/Preferences.cs
Before this change, OpenUtau defaults to scrolling which looks laggy, and it isn't that useful in tuning because users have to focus on moving notes. This PR changes the default behaviour to paging.
> Defaults to paging instead of scrolling

- OpenUtau.Plugin.Builtin/SpanishVCCVPhonemizer.cs
Uses ``t`` as a CC fallback when ``p``, ``k``, and/or ``ch`` are not present.
> [ES VCCV] Add stop consonant/affricate CC ValidateAlias

- OpenUtau.Core/Classic/ClassicRenderer.cs
- OpenUtau.Core/Classic/ExeResampler.cs
- OpenUtau.Core/Classic/IResampler.cs
- OpenUtau.Core/Classic/ResamplerItem.cs
- OpenUtau.Core/Classic/ResamplerManifest.cs
- OpenUtau.Core/Classic/UstNote.cs
- OpenUtau.Core/Classic/WorldlineResampler.cs
- OpenUtau.Core/Render/RenderPhrase.cs
- OpenUtau.Core/Ustx/UPhoneme.cs
Many resamplers are unable to parse flags correctly when there are moresampler-specific flags, because most resamplers only use single-character flags, but moresampler uses multi-character flags, such as "Mt", "Me", "Mb". To solve this issue, we can pass only the supported flags (specified in resampler manifest) into the resampler.
This filter uses the abbr of flags to check if it is supported, because a flag char could function differently on different resamplers. It is off by default to avoid breaking existing ustx files. To enable this filter, add this line into the resampler manifest:
```
expression_filter: true
```
Full resampler manifest example (tn_fnds.yaml):
```
expression_filter: True
expressions:
amp:
abbr: amp
default_value: 0
flag: A
is_flag: true
max: 100
min: -100
name: …
```
> Flag filter based on resampler manifests

- OpenUtau/App.axaml.cs
fixes a crash when opening preferences caused by en-US loading as "axaml" instead of "en-US"
also fixes singers appearing to not load due to en-US not loading as a valid sort order
> fix en-US language saving and loading

- OpenUtau.Core/Api/PhonemizerInstaller.cs
- OpenUtau.Core/Classic/ExeInstaller.cs
- OpenUtau/ViewModels/ExeSetupViewModel.cs
- OpenUtau/Views/ExeSetupDialog.axaml
- OpenUtau/Views/ExeSetupDialog.axaml.cs
- OpenUtau/Views/MainWindow.axaml.cs
After this PR, users will be able to install .dll phonemizers, .exe resamplers and wavtools by dragging it into openutau.
TODO: The installer automatically creates wine wrapper scripts when installing EXEs on Mac and Linux. I refered to https://github.com/stakira/OpenUtau/wiki/Resamplers-and-Wavtools#macos when developing, but I don't have a mac or linux device so I'm not sure if it works. Does anyone want to test it out?
> drag and drop to install .dll phonemizers, .exe resamplers and wavtools

- OpenUtau.Core/Editing/NoteBatchEdits.cs
1. Before this fix, if the starting position of the part isn't 0, PITD would be erased at the wrong position:
After this fix:
2. After this fix, if no note is selected when running pitch baking, the whole part will be processed. This behaviour is consistent with the other editing macros.
3. Each note is guaranteed to have at least two points to avoid bugs when the pitch is constant.
> Pitch Baking: fix PITD erasing region misplaced, process the whole part by default

- OpenUtau.Core/Classic/Flags/UstFlag.cs
- OpenUtau.Core/Classic/Flags/UstFlagParser.cs
- OpenUtau.Core/Classic/Ust.cs
- OpenUtau.Core/Classic/UstNote.cs
- OpenUtau.Core/Ustx/UPhoneme.cs
- OpenUtau.Test/Classic/Flags/UstFlagParserTest.cs
- OpenUtau.Test/Classic/PluginRunnerTest.cs
- Read Flags value when open Ust or run Plugin.
This PR includes https://github.com/stakira/OpenUtau/pull/705
I think merging this PR will work.
Combined with the nice fix https://github.com/stakira/OpenUtau/pull/686 we can support classic renderer flags by defining a manifest.
There are some issues with this fix that are not resolved at this time.
- Single character and no value flag support only "N" (because I don't know all flag...)
- We can do that by adding a flag to `UstFlagParser.IsSingleCharacterFlag`
- Or we might be able to tell from the manifest.(But I think it is necessary to think about dependencies)
- Adding argument expressions of type `Dictionary<string, UExpressionDescriptor>` 
- I think it would be better to change this type to some class. However, it is using as is to …
> Add support for Classic Ust Flags

- OpenUtau.Plugin.Builtin/SpanishVCCVPhonemizer.cs
A redone version of #685, now with up-to-date code.
Also ignores vowel notes within CC transitions.
> [ES VCCV] VCC/CC fix + ValidateAlias for "E" semivowel [Now with up-to-date code]

- OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
This time, there should be no issue with null alternates. When the alternate is null, it will instead return the mapped note without alternate.
**Example:** if ``[a あ2]`` does not exist, ``[a あ]`` will be returned.
> [JA CVVC] Add alternate support

- OpenUtau.Plugin.Builtin/JapaneseVCVPhonemizer.cs
Similar to #698.
This time, there should be no issue with null alternates. When the alternate is null, it will instead return the mapped note without alternate.
**Example:** if ``[a あ2]`` does not exist, ``[a あ]`` will be returned.
> [JA VCV] Add alternate support

- OpenUtau.Plugin.Builtin/ENDeltaPhonemizer.cs
Basically, the phonemizer will now check for CV notes containing diphthongs instead of checking for VV notes.
> [EN DELTA] Diphthong optimization/bug fix

- OpenUtau.Plugin.Builtin/KoreanCVCPhonemizer.cs
For some reason, whenever a romaja syllable starts with "ch", VC notes do not grab the "ch", instead returning nothing. Other consonants were unaffected.
> [KO CVC] "ch" VC fix (romaja/mixed VC)

- OpenUtau.Plugin.Builtin/ChineseCVVPhonemizer.cs
- Use new mapping style instead of legacy mapping;
- Add voice color support;
- "yan" vowel fix (it should use ``[_en2]`` instead);
- If ``[_un]`` does not exist in the oto, use ``[_en]`` instead.
I've removed alternate support for now, due to some issues.
> [ZH CVV Phonemizer] Use new mapping style + voice color support + "yan" vowel fix + "_un" ending alternative

- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
- Fixed that exp selected in the piano roll window is reselected when reloading the part
This is a somewhat forceful solution. Perhaps there is a better way.
> Fix exp selection changes when reloading part

- OpenUtau.Core/Vogen/VogenBasePhonemizer.cs
Before this fix, in vogen phonemizers, "+" is treated as space when splitting a track into phrases. If there is a short lyrical note followed by a short "+", the the consonant of the note after the "+" will be too long.
Before fix: 
After fix:
> vogen: fix too long consonant

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/Views/MainWindow.axaml.cs
Added a dialog when installing .dll phonemizers because hackers can disguise .dll as .ustx
Here is an example for this kind of attack. The filename is actually "xtsu.dll" with a unicode reverse char at the beginning
[dll_pretending_to_be_an_ustx.zip](https://github.com/stakira/OpenUtau/files/11777586/dll_pretending_to_be_an_ustx.zip)
> Add a dialog when installing .dll phonemizers

- OpenUtau.Plugin.Builtin/KoreanCVCPhonemizer.cs
- Fixes VC for tense consonants ㄲ(gg), ㄸ(dd), ㅃ(bb), ㅉ(jj) and ㄹㄹ(l):
- ㄲ will use ``[Vk]``;
- ㄸ and ㅉ will use ``[Vt]``;
- ㅃ will use ``[Vp]``.
- ㄹㄹ will use ``[Vl]``.
- Adds batchim (syllable final) end breath support.
> [KO CVC] Fix tense consonant VC + add batchim end breath support

- OpenUtau/Colors/DarkTheme.axaml
- OpenUtau/Colors/LightTheme.axaml
- Add "SystemAccentColor" in Dark/Light Theme
For the pointer over and pressed colors, the same colors are specified for now, but please change them appropriately.
They will no longer be affected by Windows theme colors :
- The color of the slider when moused over
- Text box borders
- Color of toggle switches
Verified OS : Win10
> Prevent erosion of Windows theme color

- OpenUtau.Core/Format/MidiWriter.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
Before this change, openutau remembers all the .ust and .vsqx files imported in "Open Recent". However, they are not the native file type of OpenUtau. After I imported them, I always immediately save them to .ustx and never open the original .ust or .vsqx again in OpenUtau. So here I add an option to disable remembering them in "Open Recent".
The default behaviour is unchanged: Remembering .ust and .vsqx but not remembering .mid
> Let users choose which file types to remember in "Open Recent"

- OpenUtau.Core/Util/MusicMath.cs
> Fix wordline-R stop on pitch snaps

- OpenUtau.Core/Format/Formats.cs
- OpenUtau.Core/Format/Ufdata.cs
- OpenUtau/FilePicker.cs
- OpenUtau/Views/MainWindow.axaml.cs
Ufdata is an interchange format for singing synthesis applications defined by Utaformatix. After this PR, openutau will be able to import ufdata files.
> Support ufdata import

- OpenUtau/ViewModels/PianoRollViewModel.cs
Before this change, the errors from editing macros are ignored. After this change, openutau shows a dialog when the editing macro runs into an error.
> Show a dialog when editing macros throw an error

- OpenUtau.Core/Util/SplitLyrics.cs
Bug fix : Add Japanese contracted sound processing in SplitLyrics class
Before
After
> Add Japanese contracted sound processing to EditLyrics

- OpenUtau.Core/Format/Formats.cs
Before this fix, when I click "file→import tracks", and choose a midi file, openutau will throw an error:
> fix unable to import midi in "import tracks"

- OpenUtau.Core/Classic/ClassicSinger.cs
When oto contains characters that cannot be used (such as \), an exception occurs when creating SearchTerms, but this can be ignored for practical use, so try-catch is used to ignore it.
> Ignore SearchTerms exception when loading singers

- OpenUtau/ViewModels/NotesViewModel.cs
When loading exp in the piano roll window, the number of tracks and trackNo are now checked for discrepancies.
This prevents an exception from occurring when trying to reference a track that does not exist when creating a new project with multiple tracks and parts already present.
> Fix a bug when creating a new project

- OpenUtau.Plugin.Builtin/ENDeltaPhonemizer.cs
- Refine starting CC, so that ``[- C1C2][C2C3][C3V]`` is possible (rather than using ``[- C1C2][C3V]``);
- Change ``V`` alias fallback back to ``@`` (apologies to accented voicebanks; this is the intended behavior).
> [EN DELTA] Starting CC + ValidateAlias refinement

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.es-ES.axaml
- OpenUtau/Strings/Strings.es-MX.axaml
- OpenUtau/Strings/Strings.fi-FI.axaml
- OpenUtau/Strings/Strings.fr-FR.axaml
- OpenUtau/Strings/Strings.id-ID.axaml
- OpenUtau/Strings/Strings.it-IT.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Strings/Strings.ko-KR.axaml
- OpenUtau/Strings/Strings.nl-NL.axaml
- OpenUtau/Strings/Strings.pl-PL.axaml
- OpenUtau/Strings/Strings.pt-BR.axaml
- OpenUtau/Strings/Strings.ru-RU.axaml
- OpenUtau/Strings/Strings.th-TH.axaml
- OpenUtau/Strings/Strings.vi-VN.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/Strings/Strings.zh-TW.axaml
- OpenUtau/Views/SingerSetupDialog.axaml
The old message appeared to be a warning, and most users assumed they made a mistake while selecting the text encoding. This new message describes the setup steps more clearly.
> Reworded missing info message

- OpenUtau.Core/Ustx/UExpression.cs
In the UExpression class, minimum and maximum values of voice color are no longer checked.
This prevents the colors to reset when duplicating tracks or using legacy plugins.
> Fix voice color resetting

- OpenUtau.Plugin.Builtin/ENDeltaPhonemizer.cs
- Important code refactor. Wasn't originally planning to, but it was for the better. This includes a major `ValidateAlias()` overhaul.
- Add support for `[C V]` notes (with a space).
- Added support for more accurate X-SAMPA symbols, if the voicebank has them (e.g. `r\` for the English R).
- Fixes several `ValidateAlias()` bugs and unnecessary things I added. It's now vastly more simplified (see above).
- Restore proper VCC connections, they should now function properly, even together with CC transitions.
- Restore/fix functionality of single consonants in certain positions. Yes this means the "consonants from hell" are back, just make them very quiet and/or fix the envelopes, I don't know how to fix it otherwise, I'm very sorry. Otherwise certain clusters might not work, if they're not …
> [EN Delta] Refactoring code + fix ValidateAlias bugs + restore proper VCC connections + fix single consonants

- OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
- OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
Quote from #757:
> There was a bug in both of these phonemizers where, if an append voice color contains the same suffix as on the main voice color, the voice color would fall back to having no suffix on that particular pitch. Now it will fall back on the main voice color instead, as intended.
Note that the current PR only semi-fixes this problem; the bug will still persist on VC notes, which will be null (absent) when an append voice color contains the same suffix as the main voice color. However, base notes (starting CV, base CV, VCV) will work as intended with this fix. (The reason for this is to keep supporting CV-only voice colors; otherwise, they would insert VCs of the main color, which isn't always desirable, especially with "effect voices" (growl, unvoiced/whisper).)
A workaround …
> [JA CVVC & Presamp] Semi-fix for voice color fallbacks

- OpenUtau.Core/Ustx/UProject.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Controls/ExpSelector.axaml.cs
- OpenUtau/ViewModels/ExpSelectorViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
- ~~Expressions selections are saved in preferences and are restored even when we open another project or restart it.~~
- ~~Each of the five expressions is saved just before reopening or closing the piano roll.~~
- ~~Which of the expressions to operate is saved when selected.~~
- ~~It might be nice to save individual settings for each renderer in the future, but I haven't gotten that far yet.~~
- Expressions selections are saved in ustx.
- For each ExpSelectors, which expressions is selected is always tied to the field in UProject, and the phenomenon of it being reset each time the pianoroll is opened has been resolved. They are saved as a string, and if it does not exist, it is selected in the same order as before (the 0th in Descriptors if it is the top ExpSelector).
> Save displayed expressions in Ustx

- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
- OpenUtau/Views/SliderDialog.axaml
- OpenUtau/Views/SliderDialog.axaml.cs
- New Feature: Lengthen crossfades
Lengthen the overlaps regardless of the original overlap of the oto.
Also lengthen the preutter if it can be lengthened as a result.
- Why is this feature needed?:
The oto overlap for OG UTAUs is sometimes intentionally set short(1/3 of preutter).
This is to avoid going crazy when the previous note is short.
However, in actual singing, if it can be lengthened, it will sound better.
For this reason, plugins have been developed since ancient times to lengthen crossfades, and the function has been included in 連続音一括設定(most famous plugin for VCV conversion) and presamp.
> Add Lengthen crossfades in batch menu

- OpenUtau.Core/Commands/ExpCommands.cs
- OpenUtau.Core/Editing/LyricBatchEdits.cs
- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau/OpenUtau.csproj
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/PasteParamViewModel.cs
- OpenUtau/Views/PasteParamDialog.axaml
- OpenUtau/Views/PasteParamDialog.axaml.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
New features:
- Select and paste parameters
Only selected parameters (pitch points, vibrato, expressions) of copied notes can be pasted.
Add Methods:
- UNote.GetExpression
- UNote.SetExpression
Expressions can now be handled more simply.
As a result, the following features have been optimized.
- MoveSuffixToVoiceColor
Simplified processing.
- AddTailNote
Expression of the previous note can now be carried over.
> Add "Select and paste parameters" and related methods

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/SingersViewModel.cs
- OpenUtau/Views/SingersDialog.axaml
- OpenUtau/Views/SingersDialog.axaml.cs
1. Add a "set icon" option in singers menu.
2. When setting icon or portrait, if the image file isn't inside the voicebank folder, openutau will copy it into the voicebank folder.
> Set icon for singers

- OpenUtau/ViewModels/TracksViewModel.cs
Before this change, if I want to extend the tail of a project, I have to drag and scroll many times:
https://github.com/stakira/OpenUtau/assets/54425948/29ec704a-4d41-4665-ab79-0a5e2bba3bba
After this change, I can extend the tail of a project in one drag:
https://github.com/stakira/OpenUtau/assets/54425948/e9e0e7d4-d9c8-42f7-a899-234ba05ba5de
> Make it easier to extend the tail of a project

- OpenUtau.Core/Classic/VoicebankLoader.cs
For wavs that haven't been oto'd, openutau will create a dummy `Oto` object whose `IsValid` is false and FileTrace is null, which will cause error when saving oto.
> Fix unable to save oto when the voicebank contains wavs that haven't been oto'd

- OpenUtau.Core/Enunu/EnunuRenderer.cs
* Changed the name of the structure
* Change the value used in conditional branches
* Because the original name was inappropriate for the function.
* To change the processing on the SimpleENUNUServer side as well.
> Correction of structure names, etc.

- OpenUtau/Controls/OtoPlot.cs
- OpenUtau/OpenUtau.csproj
Fixes #822
Only tested on Linux, but I imagine it should be fine on other platforms. The minor OtoPlot change was due to an Avalonia.Controls API change between 11.0.0-rc1 and 11.0.0-rc2
> Update avalonia to 11.0.4

- OpenUtau.Core/Commands/Notifications.cs
- OpenUtau.Core/Ustx/UTrack.cs
- OpenUtau/Controls/TrackHeader.axaml
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/ViewModels/TrackHeaderViewModel.cs
- OpenUtau/ViewModels/VoiceColorMappingViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/VoiceColorMappingDialog.axaml
- OpenUtau/Views/VoiceColorMappingDialog.axaml.cs
New Features:
- Voice color remapping dialog
- Voice color remapping menu in track header context menu
- When the project is opened, show the remapping dialog if the voice color lineup has been changed
- When changing voice banks, show the remapping dialog if the voice color lineup is different
Internal change:
Stores the name of the voice colors in the UTrack class
> Check and Remapping voice color

- OpenUtau.Core/Util/LyricsHelper.cs
Currently, when using the PinyinLyricsHelper, the suggested pinyin are all in uppercase. As a result, the LyricsHelper does not function properly. With this, it will be fixed so that the lowercase variant will be inserted.
> [PinyinLyricsHelper] Convert pinyin to lower variant in PinyinLyricsHelper

- OpenUtau.Test/Plugins/DeDiphoneTest.cs
- OpenUtau.Test/Plugins/DeVccvTest.cs
- OpenUtau.Test/Plugins/EnArpaTest.cs
- OpenUtau.Test/Plugins/EnToJaTest.cs
- OpenUtau.Test/Plugins/EnVCCVTest.cs
- OpenUtau.Test/Plugins/EnXSampaTest.cs
- OpenUtau.Test/Plugins/JaCvvcTest.cs
- OpenUtau.Test/Plugins/JaPresampTest.cs
- OpenUtau.Test/Plugins/JaVcvTest.cs
- OpenUtau.Test/Plugins/PhonemizerTestBase.cs
PhonemizerTestBase now has two utility methods.
SameAltsTonesColorsTest: Run phonemize test using the same alts, tones, and colors for all lyrics
RepeatString: Returns array of length `count` where all elements are string `s`
Example usage
```cs
[Theory]
[InlineData("en_delta0",
new string[] { "my", "test" },
new string[] { "- maI", "aI t", "tE", "E st-" })]
public void BasicPhonemizingTest(string singerName, string[] lyrics, string[] aliases) {
SameAltsTonesColorsTest(singerName, lyrics, aliases, "", "C4", "");
}
```
> Refactor phonemizer test utility method

- OpenUtau.Core/Classic/VoicebankInstaller.cs
- OpenUtau/ViewModels/SingerSetupViewModel.cs
If a voicebank is created on Mac and has a "_MACOSX" folder with a "._character.yaml" in it, openutau will fail to intall it on windows
> Fix unable to install vb from Mac on Windows

- OpenUtau.Core/Commands/NoteCommands.cs
- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau.Core/Util/NotePresets.cs
- OpenUtau/Controls/NotePropertiesControl.axaml
- OpenUtau/Controls/NotePropertiesControl.axaml.cs
- OpenUtau/Controls/NotePropertyExpression.axaml
- OpenUtau/Controls/NotePropertyExpression.axaml.cs
- OpenUtau/Controls/TrackHeader.axaml
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Styles/PianoRollStyles.axaml
- OpenUtau/Styles/Styles.axaml
- OpenUtau/ViewModels/NoteDefaultsViewModel.cs
- OpenUtau/ViewModels/NotePropertiesViewModel.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/Views/ExpressionsDialog.axaml
- OpenUtau/Views/NoteDefaultsDialog.axaml
- OpenUtau/Views/SingersDialog.axaml
This is equivalent to #792.
New Features:
- Textboxes and sliders now work
- Vibrato drift (move height)
This is a parameter that has existed internally in ustx up to now, but has not been used.
Currently the only way to change this parameter is to manipulate the note property.
Not yet implemented:
- Right click on the slider does not work
PointerPressed does not work well on sliders, so Focus is used instead, and it cannot determine if it is a right click or not.
- Update text box when lost focus instead of immediately
To resolve this, we need to install Avalonia.Xaml.Behaviors package.
Internal changes:
- Fix toggle button style
To correct the appearance of expanders.
> Fix Note Properties and Add vibrato drift (RERE)

- OpenUtau/Controls/NotesCanvas.cs
This is part of #774.
This change will make it possible to tell which track's ghost note when there are many tracks.
> Reflect track color in ghost notes

- OpenUtau/Colors/Brushes.axaml
- OpenUtau/Controls/TrackBackground.cs
- OpenUtau/ThemeManager.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/Views/PianoRollWindow.axaml
This is part of #774.
New feature:
- Keyboard color
By changing the color of keyboard, we can more easily recognize which track we are currently operating on.
Not only does this allow us to color the look any way we want, but it also reduces mistakes when dealing with many similar tracks (unisons, choruses, etc.).
This is only changed when preference is changed; default is off.
Minor fix:
- Fine tune the track colors
Toggle switch color fix for note properties panel is included only in #844.
> Allow to change keyboard color in PianoRoll Window

- OpenUtau.Core/Classic/VoicebankConfig.cs
- OpenUtau.Core/Vogen/VogenSingerLoader.cs
Right now, the default ``int`` value is 800, which is not ideal for portraits that are smaller in height. This fixes it so that their actual height is used, if not defined otherwise.
> [Portrait height] Set default int to 0 (no default height if below 800px)

- OpenUtau.Core/Editing/LyricBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PianoRollViewModel.cs
Lyrics available on the internet don't contain slurs. After batch inputting lyric, we often need to insert slur notes and right shift the following lyrics. 
Users can select multiple notes when running this editing macro. The lyrics of these notes will become `+~` and the lyrics of the other notes will be right shifted by the number of selected notes before them.
> editing macro: Insert slur lyric

- OpenUtau.Core/Commands/NoteCommands.cs
- OpenUtau.Core/Render/RenderPhrase.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau.Core/Util/NotePresets.cs
- OpenUtau.Test/Core/USTx/UstxYamlTest.cs
- OpenUtau/Controls/NotePropertiesControl.axaml
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/NoteDefaultsViewModel.cs
- OpenUtau/ViewModels/NotePropertiesViewModel.cs
- OpenUtau/Views/NoteDefaultsDialog.axaml
New Feature:
- Volume Link
Decreases the volume when the vibrato pitch goes down.
When this is 100%, volume will be 1.2 times to 0.2 times regardless of pitch depth.
Negative values cause phase reversal.
For now, this can only be controlled in the Note Properties panel.
> Linking vibrato and volume

- .devcontainer/devcontainer.json
After this change, developers without a Linux device can develop on Github codespace's online Linux environment.
> Add github codespace support

- OpenUtau.Core/Classic/ClassicSinger.cs
- OpenUtau.Core/Classic/VoiceBank.cs
- OpenUtau.Core/Classic/VoicebankConfig.cs
- OpenUtau.Core/Classic/VoicebankLoader.cs
- OpenUtau.Core/Enunu/EnunuSinger.cs
- OpenUtau.Core/Format/Wave.cs
- OpenUtau.Core/Ustx/USinger.cs
- OpenUtau.Test/Classic/VoicebankConfigTest.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Views/SingersDialog.axaml
- OpenUtau/Views/SingersDialog.axaml.cs
This adds a button to play the sample file of a voicebank (doesn't have to be a wav file, as long as it's a supported audio format). If a sample is not configured, it will play a random file from the voicebank folder (including subfolders). Upon clicking the button again and/or when the Singer window is closed, the sample will stop playing. It will also stop playing upon switching the singer and when opening the Voice Color menu.
This PR also adds support for reading AIFF audio files; I had coded this extension into the sample player, only to find out that OpenUtau did not support it (which is why the two are combined in one PR). Some known UTAU-compatible voicebanks (such as the old Macloids) are known to use AIFF as their audio format of choice; since it's a common format on Mac (and is …
> [Singer window] Play sample on click + [Wave.cs] Support reading AIFF format

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Views/SingersDialog.axaml
- OpenUtau/Views/SingersDialog.axaml.cs
There's always been a way to show the character.txt/character.yaml, but there was never a way to directly view the readme file. Since the readme often contains important information (such as a ToS, usage tips, etc.), I've decided to add a button to open this file.
To limit clutter on the Singers window, the readme file will open in the default external application of the operating system. If a readme.txt does not exist, a popup window will appear with the text "readme.txt not found".
> [Singers window] Add button to show readme.txt

- OpenUtau/Views/SingersDialog.axaml
- OpenUtau/Views/SingersDialog.axaml.cs
- Adjustment of button layout.
- Play audio files at random only when SingerType.Classic.
- Minimum window size changed due to overlapping button controls
> Fix singer dialog

- OpenUtau/Views/SingersDialog.axaml.cs
Before this fix, if the voicebank location isn't a folder (vogen), or the voicebank doesn't contain any audio file (nnsvs), openutau will crash.
> fix openutau crash when trying to play sample for enunu or vogen singer

- OpenUtau/Integrations/VLabelerClient.cs
When the user already created a vLabeler project in the voicebank folder, we want to use it instead of creating a new `_vlabeler.lbp` file when clicking `Edit in vLabeler` on the singer page.
If there are multiple files, we take the one updated most recently.
I tested it on my device (mac)
- when there is an existing lbp file -> existing project is correctly opened.
- when there is no existing lbp file -> a `_vlabeler.lbp` is created in the voicebank folder
> [vLabeler integration] Use existing lbp file before creating a new one

- OpenUtau/FilePicker.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/EditSubbanksViewModel.cs
- OpenUtau/Views/EditSubbanksDialog.axaml
- OpenUtau/Views/EditSubbanksDialog.axaml.cs
New Features:
- Export main voice color as prefix.map
- Import prefix.map and set it to the current field
Useful when adding new voice color.
- Reflect current value in text box when selecting rows
If multiple rows are selected, the first row is used.
> Add import / export prefix.map

- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PianoRollViewModel.cs
This PR adds an editing macro to reset all the manual phoneme aliases edits.
> Editing macro: Reset phoneme aliases

- OpenUtau/Views/PianoRollWindow.axaml.cs
stops piano roll shortcuts from blocking text box input
fixes a bug in the note properties window where text box inputs get eaten by the piano roll keyboard shortcuts.
https://github.com/stakira/OpenUtau/assets/45115987/f16e7553-084a-4023-8d00-1286c3491e70
> fix piano roll keyboard shortcuts blocking text box input

- OpenUtau/ViewModels/SingersViewModel.cs
Before this change, the "Location" button doesn't work for vogen singers. After this change, when clicking on the "Location" button for vogen singers, the .vogeon file will be shown inside the system file explorer.
> Show location for vogen voicebank

- OpenUtau/ViewModels/NotesViewModel.cs
Before this fix, OpenUtau fails to load portraits shorter than 800px unless the user manually set a portrait height in chatacter.yaml, because it tries to resize it to 0px.
After this fix, for portraits shorter than 800px, the size will be unchanged if the `portrait_height` specified in character.yaml is 0px (by default).
> fix unable to load portraits shorter than 800px

- OpenUtau.Core/Commands/ExpCommands.cs
- OpenUtau/ViewModels/NotePropertiesViewModel.cs
fixes a bug where note bends become "entangled" when changing portamento properties in the note properties window
https://github.com/stakira/OpenUtau/assets/45115987/597a501d-ac11-498b-a3b4-e0db6c58f529
> fix note bend entanglement when changing portamento in note properties

- OpenUtau/ViewModels/NotesViewModel.cs
Before this change, we can't ctrl-click to select non-consecutive notes. When we ctrl-click on a unselected note, the other notes will be deselected. We can only box select all the notes between the first and the last note we want, and ctrl-click to deselect unwanted notes, and we have to do this process again if we deselected one more note by mistake.
After this change, we can ctrl-click to add note into selection without deselect the other notes, making it easier to select non-consecutive notes.
> ctrl-click to add note into selection without deselecting the other notes

- OpenUtau.Plugin.Builtin/Data/en-xsampa.template.yaml
- OpenUtau.Plugin.Builtin/EnXSampaPhonemizer.cs
- Fixes an issue where ``ValidateAlias()`` isn't properly called on diphthongs.
- Added Vocaloid-style rhotic vowel fallbacks for VCC transitions and endings.
- Some more ``ValidateAlias()`` function refinement.
- Added some fallback diphthong sounds, to properly use in custom dictionaries and/or phonetic hint.
> [English X-SAMPA Phonemizer] ValidateAlias() bug fix/refinement + some vowel fixes/refinements

- OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
When applying nearest interpolation in some cases, the previous wrong implementation to collect index groups of continuous rest notes can unexpectedly mask non-rest note pitches. This leads to wrong results when generating DiffSinger auto-pitch.
Before this fix:
After this fix:
**The bug affects all DiffSinger voicebanks with pitch predictor. This PR is urgent and should be merged as soon as possible.**
> [DiffSinger] Fix note pitch masked unexpectedly when applying nearest interpolation

- OpenUtau.Core/DiffSinger/DiffSingerSpeakerEmbedManager.cs
In the previous implementation, when an exception is raised during loading *.emb files from disk (for example, file not found), the loop is immediately interrupted and the wrong speaker embedding tensor, which was filled with zeros at the beginning, remains in memory as a member variable. This makes DiffSinger produce wrong and noisy results.
After this fix, the embedding tensor will not be stored as member variable until all *.emb files are loaded correctly.
> [DiffSinger] Fix invalid tensor in memory when errors occur during *.emb loading

- OpenUtau.Core/Classic/ClassicSinger.cs
- OpenUtau.Core/Classic/VoiceBank.cs
- OpenUtau.Core/Classic/VoicebankConfig.cs
- OpenUtau.Core/Classic/VoicebankLoader.cs
- OpenUtau.Core/DiffSinger/DiffSingerSinger.cs
- OpenUtau.Core/Enunu/EnunuSinger.cs
- OpenUtau.Core/SingerManager.cs
- OpenUtau.Core/Ustx/USinger.cs
- OpenUtau.Core/Vogen/VogenSinger.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/TrackHeaderViewModel.cs
- OpenUtau/Views/SingersDialog.axaml
This PR allows voicebank developers declare how to call their voicebanks in different languages in character.yaml. For example:
```yaml
name: Namine Ritsu
localized_names:
ja-JP: 波音リツ
zh-CN: 波音律
```
available language codes: `en-US`, `de-DE`, `es-ES`, `es-MX`, `fi-FI`, `fr-FR`, `id-ID`, `it-IT`, `ja-JP`, `ko-KR`, `nl-NL`, `pl-PL`, `pt-BR`, `ru-RU`, `th-TH`, `vi-VN`, `zh-CN`, `zh-TW`
> singer name localization

- OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
- Fixes voice color and tone shift by mapping the aliases. Legacy mapping has been removed, as it is no longer necessary;
- Add alternate support;
- Extend end breath support (``R2``). Also works through alternate.
> [KO VCV Phonemizer] Voice color fix + alternate support + extend end breath support

- OpenUtau.Plugin.Builtin/ChineseCVVCPhonemizer.cs
Right now, VCs use the pitch of the current note. However, making it use the pitch of the previous note gives a more desirable result. Note that this PR does not affect voice colors.
> [ZH CVVC] Make VC use pitch of previous note

- OpenUtau/ViewModels/NotesViewModelHitTest.cs
- OpenUtau/Views/NoteEditStates.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
This PR supports resizing notes from their heads.
- Each note now has two resizing areas: its tail and its head. When the two areas overlap (when the note is extremely short), the tail area is the preferred area to be regarded as hit.
- `NoteHitInfo` gets a new attribute `hitResizeAreaFromStart`. When its `hitResizeArea` is set to true, this attribute will help determine whether the note is being resized from the head or the tail.
- Attribute `resizeNext` of `NoteResizeEditState` is generalized to `resizeNeighbor` to support similar behavior when resizing with Alt pressed from either the head and the tail.
- Batch resizing (resize when there are multiple note selections) from the heads is also implemented.
Demo:
https://github.com/stakira/OpenUtau/assets/70186231/ea09fa4d-3958-4fd3-8033-43 …
> Support resizing notes from their heads

- OpenUtau.Core/DocManager.cs
Fixed to not show a dialog asking to save the project when trying to close a freshly created project.
> Don't show save dialog for new project

- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PianoRollViewModel.cs
If multiple notes start at the same time, only the one with the highest tone will be kept
If one notes's end is overlapped by another note, the end will be moved to the start of the next note
Though similar to auto legato, this editing macro only trim notes that are too long. It won't fill up the space between notes. It will also remove the notes that start at the same time with another note but have a lower tone.
> Editing macro: fix overlapping notes

- OpenUtau.Core/Classic/VoicebankLoader.cs
Loading of prefix.map is not needed at startup, so it was put off.
> Faster startup

- OpenUtau.Plugin.Builtin/ChineseCVVCPhonemizer.cs
This fixes an issue regarding plain CV initials. I've also separated the voice color for CV and VC.
I've also decided to add support for VC length calculation through velocity values.
> [ZH CVVC Phonemizer] Fix CV handling: Starting CV fix + separate CV and VC voice color + Add VEL length calculation for VC

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Styles/Styles.axaml
The font used for the text boxes is a bit hard to read in Japanese, so changed to the same font as the text and labels.
It may depend on the environment, but it will not have any adverse effect.
This is largely a personal preference, so please merge if necessary.
> Fix TextBox font

- OpenUtau.Core/PlaybackManager.cs
- OpenUtau/Views/MainWindow.axaml.cs
Check if wav cannot be written when exporting tracks or mixdown because they are in use or for other reasons.
> Check wav file writeable when exporting

- OpenUtau.Plugin.Builtin/GermanVCCVPhonemizer.cs
This is a small fix; I noticed I had forgotten to define ``9`` as a vowel. This PR fixes that.
I also decided to adjust consonant length calculation.
> [DE VCCV Phonemizer] Add missing vowel sound + consonant length adjustment

- OpenUtau.Plugin.Builtin/KOtoJAPhonemizer.cs
This phonemizer lets Japanese voicebanks sing in Korean.
- Supports Hangul and phonetic hint (based on Japanese romaji, since it uses Japanese phonemes).
- Please note that diphthongs are their own vowel phonemes, e.g. ``[g ya]`` (*NOT* ``[gy a]`` or ``[g y a]``).
- Stuff like ``[s i]``, ``[s ya]`` etc. works for し, しゃ etc., this has to do with Korean pronunciation (すぃ would be ``[s wi]``).
- Supports VCV, CVVC, CV.
- Supports alias fallbacks (e.g. くぁ→か if the former is not present).
- VCV has priority on open syllables, whereas batchim (syllable endings) prioritize VC aliases.
- CVVC and then CV get priority before a VCV fallback is used (e.g. ``[a k][くぁ]`` over ``[a か]``).
- Supports VC consonant fallbacks.
- Supports crossfade vowels (``[* V]``), this includes batchim that end in ん.
- …
> Add Korean-to-Japanese Phonemizer

- OpenUtau.Core/Enunu/EnunuPhonemizer.cs
After this change, BPM is taken into account when hashing for ENUNU timing cache.
> Fix ENUNU phonemizer broken after BPM editing.

- OpenUtau.Plugin.Builtin/SyllableBasedPhonemizer.cs
This PR makes it so that aliases can now also be extended across different subbanks in syllable-based phonemizers. Note that the option to restrict it to only the same subbank has not been removed; I've simply made it so that it will be up to the phonemizer developers to decide.
The reason I am making this PR is because the current spec can cause issues when extending diphthongs in certain languages (including English) across different pitches and/or voice colors.
In order to re-implement the previous spec into a phonemizer, the code should look something like this:
```
if (CanMakeAliasExtension(syllable) && AreTonesFromTheSameSubbank(syllable.tone, syllable.vowelTone))
```
or, in negative form:
```
if (!CanMakeAliasExtension(syllable) || !AreTonesFromTheSameSubbank(syllable.tone, …
```
> [SyllableBasedPhonemizer API] Make alias extension restriction to same subbank optional

- OpenUtau.Core/DiffSinger/DiffSingerSinger.cs
Add support for custom vocoders for DiffSinger models. This does not overwrite the current vocoder system, but instead first checks for a "dsvocoder" folder that would contain "vocoder.yaml" and would point to an ONNX model of the vocoder IF the `vocoder` line in the main "dsconfig.yaml" file is null.
> Add support for a custom vocoder for DiffSinger singer

- OpenUtau.Core/Classic/WorldlineRenderer.cs
- OpenUtau.Core/Classic/WorldlineResampler.cs
- OpenUtau.Core/PlaybackManager.cs
- OpenUtau.Core/Render/RenderEngine.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
Changes:
- Fixed parent methods could not know exceptions handled by deep methods
- Fixed double display of error dialog due to catching and re-throwing exceptions several times
- Fixed UI thread cannot catch exceptions because playback is an asynchronous process
Verified:
- When exceptions is thrown during pre-rendering, write error in log without error dialog
- When exceptions is thrown during playback, show an error dialog and stop playback
- When exceptions is thrown during export of mixdown or tracks, show an error dialog and do not export
> Improved stability of rendering

- OpenUtau/Views/MessageBox.axaml
- OpenUtau/Views/MessageBox.axaml.cs
Avalonia does not support hyperlinks, so the buttons just look like that.
The URL is always preceded and followed by a new line.
> Make the URL in message box look like hyperlink

- OpenUtau.Core/Util/Onnx.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- Modified to fix invalid values in prefs.json
- Fixed to open preferences window even if there is an invalid value in prefs.json
- Display "(None)" when additional singer path does not exist
> Improved stability of preferences

- OpenUtau.Core/BaseChinesePhonemizer.cs
- OpenUtau.Core/DiffSinger/DiffSingerChinesePhonemizer.cs
- OpenUtau.Core/DiffSinger/DiffSingerG2pPhonemizer.cs
- OpenUtau.Core/DiffSinger/DiffSingerPhonemizer.cs
- OpenUtau.Core/G2p/ZhG2p.cs
- Before this PR, if the lyric is space-separated phoneme list, the phonemizer result will be misplaced. 
This bug is fixed in this PR. 
- Add a separate diffsinger Chinese phonemizer and remove the hanzi to pinyin converter from the default diffsinger phonemizer to prevent similar bugs in the future.
> Fix diffsinger phoneme misplace if lyric contains space; separate diffsinger Chinese phonemizer

- OpenUtau.Core/Classic/VoicebankLoader.cs
Fixed a bug that a blank line in oto.ini created an empty oto, which caused voice banks to fail to load.
> Fix creation of empty Oto from blank line in otoini

- OpenUtau/Views/MainWindow.axaml.cs
Before this fix, if the user opens a ustx made by another user, and he hasn't installed the singer that the ustx uses, and opens the singer window, OpenUtau will show an error.
> fix error when opening singer view if the singer used in the ustx doesn't exist

- OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
This makes it so that when ``[MUSTVC]`` is set to ``1`` in the presamp.ini file, a VC phoneme will be inserted even on short notes. When set to ``0`` (which is the default), this will not happen.
> [Japanese Presamp Phonemizer] Add option for MUSTVC

- OpenUtau.Plugin.Builtin/ChineseCVVCPhonemizer.cs
This automatically adds a syllable ending to a note if the next neighbor is null (and if it exists in the oto). This function was added due to the existence of closed syllables and falling diphthongs in Chinese (unlike Japanese, where this can be optional). Currently, this has to be done manually on a separate note, which can be a relatively easy oversight.
Placing the ending on a separate note is still possible, if preferred. It also should not conflict with any end breaths etc.
Feedback is welcome.
> [ZH CVVC] Automatically add syllable ending if present (if next neighbor is null)

- OpenUtau.Plugin.Builtin/CantoneseCVVCPhonemizer.cs
This phonemizer works mostly the same as the Chinese CVVC Phonemizer, except when typing hanzi lyrics, they will be converted to jyutping instead of pinyin. A presamp.ini file is required here as well. This is a more practical solution than what I attempted with #960.
As I've mentioned in #959, I might split the jyutping conversion off into a "Base Cantonese Phonemizer" at one point, if this turns out to be more practical.
Feedback is welcome; if I am missing anything, please tell me so I can improve this.
> Add Cantonese CVVC Phonemizer

- OpenUtau.Core/Classic/ExeWavtool.cs
- OpenUtau.Core/Render/Renderers.cs
After this change, worldline resampler can be used together with external wavtool. There will no longer be "no application set to open the document" error when switching to worldline mid-project with ENE expression. Worldline will also be listed as a resampler option when an external wavtool is used.
> Support using worldline resampler together with external wavtool

- OpenUtau.Core/DiffSinger/DiffSingerJyutpingPhonemizer.cs
- OpenUtau.Core/Vogen/VogenYuePhonemizer.cs
Before this change, these two Cantonese phonemziers are under the same category with mandarin Chinese phonemizers. LotteV has created a ZH-YUE category, so here I move DIFFS ZH-YUE and VOGEN ZH-YUE into this category.
> Move DIFFS ZH-YUE and VOGEN ZH-YUE to ZH-YUE category

- OpenUtau.Core/Util/TimeAxis.cs
After this fix, when opening a ustx project whose first time signature isn't at 0 (produced by third-party softwares), openutau won't crash. Instead, it will show an error dialog.
> Fix openutau crash when opening a ustx project whose first time signature isn't at 0

- OpenUtau.Core/KoreanPhonemizerUtil.cs
- Added KoreanPhonemizerUtil.cs, and This class will be used in **Diffsinger Korean Phonemizer**, **other Multiple Korean Phonemizers(including Classic)**.
- Implementing Korean Phoneme Variation(like 꽃망울에 to [꼰망우레]), Jamo separation(like 간 to ㄱㅏㄴ), Jamo merge(like ㄱㅏㄴ to 간) in Each phonemizers makes Korean Plugin developers struggle.... So I made KoreanPhonemizerUtil, to increase Productivity and Code re-using.
- Also supports .ini management, currently used by KO CV Phonemizer & KO ENUNU Phonemizer.
- If this branch merged, I want to PR two Classic Korean Phonemizers and Diffsinger Korean Phonemizer which using this class. 👀 (+ [23.12.28] Korean ENUNU Phonemizer uses this class too)
> Add KoreanPhonemizerUtil

- OpenUtau/Strings/Strings.ko-KR.axaml
This is a PR with the following fixes for the Korean translation. It still needs to be reviewed several times.
- Fix mistranslations
- Add missing translations
- Edit terms for consistency
- Proofread sentences
한국어 번역에 대해 다음 수정 사항을 담은 PR입니다. 아직 여러 번 검토가 필요합니다.
- 오역 수정
- 누락된 번역 추가
- 단어 난립 교정
- 문장 다듬기
Here's a summary of the changes. My English isn't exactly great, so I won't be able to translate everything into English, but I've added subheadings for English-speaking contributors.
세부 변경 내용은 다음과 같습니다. 영어 실력이 딱히 뛰어난 정도는 아니어서 모든 내용을 영어로 전해 드리진 못하겠습니다. 다만 영어권 기여자분들을 위해 소제목을 추가했으니 참고해 주세요.
- **과도한 '해요체' 교정 / Correct sentences that are unnaturally forced into a single grammatical style.**  
보통 한국어 화자는 적당히 격식을 갖추는 자리에서 하십시오체와 해요체를 적절히 섞어서 사용합니다. "오류가 발생했습니다. 다음을 확인해 주세요."라든지, "오늘까지는 어려울 것 같습니다. …
> Improve Korean Translation, Add missing translation

- OpenUtau.Core/KoreanPhonemizerUtil.cs
- OpenUtau.Plugin.Builtin/BaseKoreanPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCBNNPhonemizer.cs
- Improved Korean CBNN Phonemizer.
- Supports Phoneme Variation, Improved result's Quality by adjusting end-consonants' positions in detail, and It Inserts "- Phoneme(like "n -")" more properly. Also supports Phoneme hints input(like 눈[- nu, un, n -], 사[- ssa, a r], 람[ra1, am, m -]).
- It also became to handle several kinds of missing phonemes. Now it automatically detects suffixed-CV phoneme(like "gya3") or VC phoneme, so even a singer that has some minor missing phonemes can use this phonemizer normally. (In result, it increased user convenience.) 
- This is Branch after (Should be merged after) #990
> Improve KoreanCBNNPhonemizer

- OpenUtau.Core/KoreanPhonemizerUtil.cs
- OpenUtau.Plugin.Builtin/BaseKoreanPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCBNNPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVPhonemizer.cs
- Added Korean CV Phonemizer(CLASSIC).
- Since Korean CV Voicebanks have many variations in Alias, It uses `Ko-CV.ini` to Handle Various CV voicebanks.
(for example, 시 is used as "shi" in some VBs and "si" in others, Batchim 아-ㄴ is used as "an" in some VBs and "a n" in others... so on. We are calling ALL of them as "Korean CV Voicebanks", but They are commonly using Similar, but Different phoneme symbols in some part.) 
- Supports Phoneme hints input(like 냥[nya, a ng]), Detailed phoneme position adjustments(Especially at end consonants) for better synthesize quality, and Korean Phoneme Variation.
- This is Branch after (Should be merged after) #991
> Add KoreanCVPhonemizer

- OpenUtau.Core/DiffSinger/DiffSingerKoreanPhonemizer.cs
- OpenUtau.Core/KoreanPhonemizerUtil.cs
- OpenUtau.Plugin.Builtin/BaseKoreanPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCBNNPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVPhonemizer.cs
- Added Diffsinger Korean Phonemizer.
- Supports Korean Phoneme Variation, Adjusts positions of semivowels(y, w) so Diphthongs have no more Loosy sounds.
- This is Branch after (Should be merged after) #992
> Add DiffSingerKoreanPhonemizer

- OpenUtau.Core/DiffSinger/DiffSingerKoreanPhonemizer.cs
- OpenUtau.Core/Enunu/EnunuKoreanPhonemizer.cs
- OpenUtau.Core/KoreanPhonemizerUtil.cs
- OpenUtau.Plugin.Builtin/BaseKoreanPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCBNNPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVPhonemizer.cs
- Supports Korean Phoneme Variation, User-defined phoneme(jamo) dictionary by `jamo_dict.yaml` , and Two types of semivowel notation("g y a" for "갸", or "gy a" for "갸") by `ko-ENUNU.ini`. 
- This is Branch after (Should be merged after) #993
> Add ENUNUKoreanPhonemizer

- OpenUtau.Core/Format/Formats.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PreferencesDialog.axaml
When importing tracks, sometimes the user wants to keep their original timeaxis. This PR let the user to choose the behaviour when importing. The user can choose "Always", "Never", or "Ask me each time".
If "Ask me each time" is selected, openutau will show a dialog with the tempo list when importing tracks:
> Add an option to import tempo when importing tracks

- OpenUtau.Plugin.Builtin/EnXSampaPhonemizer.cs
This will distinguish between beginning consonants of the current word and ending consonants of the previous word. Fallbacks are supported. I decided to implement this since in English, starting and ending consonants can sound quite different.
Some visual examples:
Current word CCV vs previous word spaced CC. The current word CC can still fall back to spaced CC (after non-spaced CC).
VCV with consonant from previous word vs. CVVC with consonant from current word. Falls back to regular VCV first, then CVVC.
**TODO:** Do something similar with VCV that contain multiple ending consonants? This is a bit more complicated which is why I'm waiting to implement it. Right now, only start consonants are supported, otherwise it falls back to CVVC with CC.
> [EN X-SAMPA] Distinguish between current word CC and previous word CC

- OpenUtau.Core/Api/G2pDictionary.cs
- OpenUtau.Core/Api/G2pFallbacks.cs
- OpenUtau.Core/Api/G2pPack.cs
- OpenUtau.Core/Api/G2pRemapper.cs
- OpenUtau.Core/Api/IG2p.cs
- OpenUtau.Plugin.Builtin/ChineseCVVPhonemizer.cs
- OpenUtau.Plugin.Builtin/PhonemeBasedPhonemizer.cs
This PR adds an IsGlide method to IG2p that tells whether a phoneme is a semivowel or liquid sound, like `y`, `w`, `l`, `r` in English. 
In "Consonant - Glide - Vowel" syllables such as "grass", glide phoneme should be put after the start position of the note.
I've tested some external dll phonemizers released before this change. They work successfully as before.
> G2p: add IsGlide method; EN ARPA: support glide phonemes.

- OpenUtau.Plugin.Builtin/SpanishSyllableBasedPhonemizer.cs
This is an important refactor that has been long overdue.
- Fixes several bugs, mostly related to ``ValidateAlias()`` as well as some others.
- Adds custom dictionary support (``es-syl.yaml``). No dictionary template has been added; I might do this if there's demand.
I might take a look at the other Spanish phonemizers as well at some point, though this one was arguably the most outdated.
> [ES SYL] Phonemizer refactor + custom dictionary support

- OpenUtau/Program.cs
This PR enables support for IME input methods that does not appear to be supported when OpenUtau is compiled for Linux.
Tested working using IBus w/ Anthy. Built and tested on windows as well, the option does not appear to affect other platforms
Reference: https://github.com/AvaloniaUI/Avalonia/issues/6155
> Enable IME input on X11 platforms such as Linux

- OpenUtau.Core/DiffSinger/DiffSingerRhythmizerPhonemizer.cs
Diffsinger Rhythmizer phonemizer is a legacy solution used by old diffsinger voicebanks. Since the diffsinger rhythmizer is only used by Chinese voicebanks and there is no need to train new rhythmizer models now (because we have dsdur model), this PR directly adds the hanzi to pinyin converter to the rhythmizer phonemizer instead of creating a separate ZH one.
> Diffsinger Rhythmizer phonemizer: Support hanzi input

- OpenUtau.Core/Classic/ClassicSingerLoader.cs
- OpenUtau.Core/Classic/VoicebankLoader.cs
- OpenUtau.Core/SingerManager.cs
- OpenUtau.Core/Ustx/USinger.cs
- OpenUtau.Core/Util/PathManager.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau.Core/Vogen/VogenSingerLoader.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
Having the same search range for singers as for OG UTAU is useful for users who share a voice folder.
This can be selected in Preferences.
Bug Fixes:
- When the Singers folder is selected as AdditionalSingerPath, it is not loaded twice.
- Avoided loading singers with the same folder name.
> Add option to load only top directories of singers

- OpenUtau.Core/Util/OS.cs
I found on macOS, when my vb's path contains a whitespace, the "open location" and "generate error report" features don't work properly, so I added `"` in the path passed to the CMD.
I tested only on macOS, so could you help test on Windows? I'm not sure whether the fix is redundant or making a problem on Windows.
> Fix file system path handling by adding surrounding ""

- OpenUtau.Core/Ustx/USinger.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Controls/TrackHeader.axaml
- OpenUtau/Controls/TrackHeader.axaml.cs
- OpenUtau/ViewModels/MenuItemViewModel.cs
- OpenUtau/ViewModels/TrackHeaderViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
- OpenUtau/Views/PreferencesDialog.axaml.cs
New Features:
- Singer favorite function
These are stored in the preferences.
- Reloading singers in the Preferences dialog (e.g., when singer path is changed)
Specification Changes:
- Recently used singers are now sorted in the order in which they were used.
- Now notifies when there is no singer.
- When selecting singers, paths are now shown on mouse over.
Known Issues (I tried these things but could not fix them):
- Favorite status in the singer selection menu is not bound in real time.
- Heart button is small.
- I want to move the heart button to the far right.
> Add singer favorite function

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.de-DE.axaml
- OpenUtau/Strings/Strings.es-ES.axaml
- OpenUtau/Strings/Strings.es-MX.axaml
- OpenUtau/Strings/Strings.fi-FI.axaml
- OpenUtau/Strings/Strings.fr-FR.axaml
- OpenUtau/Strings/Strings.id-ID.axaml
- OpenUtau/Strings/Strings.it-IT.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Strings/Strings.ko-KR.axaml
- OpenUtau/Strings/Strings.nl-NL.axaml
- OpenUtau/Strings/Strings.pl-PL.axaml
- OpenUtau/Strings/Strings.pt-BR.axaml
- OpenUtau/Strings/Strings.ru-RU.axaml
- OpenUtau/Strings/Strings.th-TH.axaml
- OpenUtau/Strings/Strings.vi-VN.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/Strings/Strings.zh-TW.axaml
- OpenUtau/ThemeManager.cs
- OpenUtau/ViewModels/TrackHeaderViewModel.cs
After this change, OpenUtau will show localized name for each singing language it supports when selecting phonemizer.
The localized names of each language come from https://github.com/symfony/symfony, and are converted to openutau format using the following script:
```python
#symfony repo contains the names of one language in different languages
#https://github.com/symfony/symfony
#This script converts them to openutau's localization file format.
#Before running this script, please run the following commands:
#git clone https://github.com/symfony/symfony
#git clone https://github.com/stakira/OpenUtau
#pip install py_linq
from   typing  import List, Dict, Tuple
import pathlib
from   py_linq import Enumerable
from   OpenUtau.Misc.sync_strings import file_to_dict, dict_to_file
oRoot = …
```
> language name localization

- OpenUtau.Core/DiffSinger/DiffSingerBasePhonemizer.cs
After this change, if a phoneme is specified as "semivowel" or "liquid" in dsdict, it will be treated as a glide phoneme by diffsinger phonemizers. In "Consonant - Glide - Vowel" syllables such as "grass", glide phoneme will be put after the start position of the note.
> diffsinger phonemizers: support glide phonemes

- OpenUtau.Core/Vogen/VogenSingerLoader.cs
Before this change, if "load all depth folders" is turned off, vogen voicebanks won't show up because openutau try to load them in subfolders of `Singers` folder instead of `Singers` folder where vogen voicebanks install to. This bug is fixed in this PR
---
Note for developers: unlike utau, nnsvs and diffsinger voicebanks that are folders with character.txt and character.yaml, vogen voicebanks are .vogeon files just inside "Singers" folder in your openutau data path.
> fix not loading vogen voicebanks if "load all depth folders" is turned off

- OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
- OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
- OpenUtau.Core/DiffSinger/DiffSingerUtils.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
- OpenUtau.Core/DiffSinger/DiffSingerVocoder.cs
- Vocoder's hop size and sample rate should be equal to that of the acoustic model. If they aren't the same, openutau will show an error dialog.
- Hop size is 512 by default. Sample rate is 44100 by default. If you trained a model with a different hop size or sample rate, you should specify in dsconfig.yaml
- Variance model can have a different hop size and sample rate than acoustic model. If they're different, openutau will resample the variance curves.
- The shape of vocoder output should be (1, length). If it isn't, openutau will show an error dialog.
> diffsinger renderer: stricter vocoder-acoustic compatibility check

- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
This PR adds a toggle for the pen plus tool to be the default tool when OpenUtau is first loaded, and when pressing 2 instead of CTRL+2
> Add toggle for defaulting to pen plus too

- OpenUtau.Core/Classic/ClassicSinger.cs
- OpenUtau.Core/DiffSinger/DiffSingerSinger.cs
- OpenUtau.Core/Enunu/EnunuSinger.cs
- OpenUtau.Core/Format/OpusOggWaveReader.cs
Open voicebank icon file read-only.
Fix an "[ERR] Failed to load avatar data" issue if current user can not open the file for writing.
> Open voicebank icon file read-only

- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
Fix some keyboard input issues:
1. Fix some key bindings that do not match the comments:
`Ctrl+D`
`Shift+]`
2. Try to fix a focus issue when the user leave the Menu but the focus could still be on the MenuItem, making Home/End and other navigation keys do not work as expected (they still navigate in the menu region and can not move the playback or note position).
This issue could happen if the menu is closed when the mouse pointer is on the tool bar or if the user use Alt/Esc keys to navigate the menu.
I'm not sure whether not not it is a correct way to fix this by explicitly setting the main window focusable.
> Fix keyboard input: fix focus onMenuClose and fix some key bindings

- OpenUtau.Core/Commands/ExpCommands.cs
- OpenUtau.Core/Editing/LyricBatchEdits.cs
- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau.Core/Ustx/UPhoneme.cs
- OpenUtau/Controls/ExpressionCanvas.cs
- OpenUtau/Controls/NotePropertyExpression.axaml
- OpenUtau/ViewModels/NotePropertiesViewModel.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/NoteEditStates.cs
In implementing track expression and phonemizer expression in the future, we need to clearly distinguish whether a phoneme has a value or not.
- To distinguish between "set value to 100" and "no value (default value of 100)", SetNote/PhonemeExpressionCommand will accept null as well as float.
- In the expression panel and properties panel, the presence or absence of a value can be visually determined.
- Implement logic for "phonemizerExpressions".
The ability for the phonemizer to recommend an expression(voicecolor, P flag, etc.) and for the user to override it.
https://github.com/stakira/OpenUtau/assets/130257355/85e0e071-bc48-4417-9661-0827158eb5e7
(prototype)
> Add "no value" to expression

- OpenUtau.Core/PlaybackManager.cs
- OpenUtau.Core/Render/RenderEngine.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.de-DE.axaml
- OpenUtau/Strings/Strings.es-ES.axaml
- OpenUtau/Strings/Strings.es-MX.axaml
- OpenUtau/Strings/Strings.fi-FI.axaml
- OpenUtau/Strings/Strings.fr-FR.axaml
- OpenUtau/Strings/Strings.id-ID.axaml
- OpenUtau/Strings/Strings.it-IT.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Strings/Strings.ko-KR.axaml
- OpenUtau/Strings/Strings.nl-NL.axaml
- OpenUtau/Strings/Strings.pl-PL.axaml
- OpenUtau/Strings/Strings.pt-BR.axaml
- OpenUtau/Strings/Strings.ru-RU.axaml
- OpenUtau/Strings/Strings.th-TH.axaml
- OpenUtau/Strings/Strings.vi-VN.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/Strings/Strings.zh-TW.axaml
- OpenUtau/ViewModels/PlaybackViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
- OpenUtau/Views/PreferencesDialog.axaml
This pull request tries to add a feature that only renders and plays selected region in the PianoRollWindow.
Only a simple play-region command via Alt+Space is provided in this PR.
It seems to work. But the UI interaction may need further improvement.
> Add a feature to only render and play selected region

- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/TracksViewModel.cs
adds a check to stop `playPosXToTickOffset` from becoming `NaN`
fixes a visual bug with the piano roll when first opened while the project is playing due to `NaN` propagating to `TickOffset`
> fix bugged piano roll when first opened while the project is playing

- OpenUtau.Core/Api/Phonemizer.cs
- OpenUtau.Core/Api/PhonemizerRunner.cs
- OpenUtau.Core/BaseChinesePhonemizer.cs
- OpenUtau.Core/Enunu/EnunuKoreanPhonemizer.cs
- OpenUtau.Core/Enunu/EnunuPhonemizer.cs
- OpenUtau.Core/MachineLearningPhonemizer.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau.Core/Ustx/UPart.cs
- OpenUtau.Core/Vogen/VogenBasePhonemizer.cs
- OpenUtau.Plugin.Builtin/CantoneseSyoPhonemizer.cs
- OpenUtau.Plugin.Builtin/ChineseCVVCPhonemizer.cs
- OpenUtau.Plugin.Builtin/ChineseCVVPhonemizer.cs
- OpenUtau.Plugin.Builtin/EnunuOnnx/EnunuOnnxPhonemizer.cs
- OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
- OpenUtau.Test/Plugins/PhonemizerTestBase.cs
- OpenUtau/Views/MainWindow.axaml.cs
New Feature:
- Phonemizer expression:
Phonemizer can suggest expressions such as flags and volumes. Expressions specified in the UI will always take precedence over those suggested by the phonemizer.
If phonemizer suggest an expression that is not in the project, it will be ignored.
Changes:
- Phonemizers can optionally get projects and tracks: Phonemizer.SetUp()
It is possible to get voice colors, and to get the track expression when it is implemented in the future.
- JA VCV&CVVC Phonemizer
The color of VC will be that of CV unless otherwise specified. In the future I would like to adjust the volume of consonants.
Fix:
- Fixed a bug in the Paste Selected Parameters menu where it would only paste to the first phoneme when the note to paste to had no expression: UNote.cs int[] …
> Add phonemizer expression

- OpenUtau.Core/DiffSinger/DiffSingerConfig.cs
- OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
- OpenUtau.Core/DiffSinger/DiffSingerVocoder.cs
The following checks are performed between DiffSinger vocoder and acoustic model:
- `sample_rate`, `hop_size`, `num_mel_bins`, `mel_fmin`, `mel_fmax` must be equal
- `mel_scale` must be equal and must be `slaney` or `htk`
- `mel_base` must be `10` or `e` (mel will be transformed between mismatching values)
> [DiffSinger] Add more mel checks between vocoder and acoustic model

- OpenUtau.Core/OpenUtau.Core.csproj
- OpenUtau.Test/Core/USTx/UstxYamlTest.cs
This PR fixes https://github.com/stakira/OpenUtau/issues/1040 where strings startswith "\t- " can't be written into yaml file correctly
- update yamldotnet to 15.1.2
- add unit test
> fix strings startswith "\t- " in yaml

- OpenUtau.Core/Classic/Plugin.cs
I have only been able to test it on Windows, so please let me know if there are any problems on a Mac.
> Fix plugin failing to run when OU path contains space

- OpenUtau.Core/DiffSinger/DiffSingerSinger.cs
Before this PR, if one diffsinger voicebank has mistake (for example, its dsconfig.yaml is invalid, or the phonemes.txt file doesn't exist), OpenUtau will fail to load all the voicebanks.
> Diffsinger: fix openutau unable to load the other voicebanks if one diffsinger has mistake.

- OpenUtau.Core/Ustx/USinger.cs
- OpenUtau.Core/Ustx/UTrack.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/App.axaml
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/Converters.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- Fixed two English choices for language in preferences
- Fixed untranslated singer names on tracks
- Remove unused properties: USinger.DisplayName, UTrack.SingerName
- Fixed to not translating when the singer's translation language is invariant culture
- Voicebank authors can provide the default name of the non-English singer along with the English name.
> Fix singer name translation

- OpenUtau.Core/Commands/NoteCommands.cs
- OpenUtau.Core/Ustx/UPart.cs
- OpenUtau.Core/Ustx/UPhoneme.cs
Fixed a bug in which phoneme override was misjudged as being present because resetting a phoneme of PhonemeOverride would result in string.Empty instead of null.
> Fix UPhonemeOverride.phoneme

- OpenUtau.Core/Commands/NoteCommands.cs
- OpenUtau.Core/Ustx/UPart.cs
- OpenUtau/ViewModels/TracksViewModel.cs
- Added storing the length of the part in ustx.
- When entering and resizing notes, the part is automatically extended by one measure when the length of the part is less than one measure remaining.
- The interval between the end of note and the end of part is now non-zero.
https://github.com/stakira/OpenUtau/assets/130257355/60fc422d-975f-4fa6-bf2b-a1266063860a
> Part duration enhancement

- OpenUtau/ViewModels/NotePropertiesViewModel.cs
The combo box is reset each time a note is selected, making it easier to select a preset.
> Reset preset combo box in the note properties panel

- OpenUtau/ViewModels/MainWindowViewModel.cs
When the main window is hidden, it is easier to see if it is saved or not.
> Move save status(*) to the top of window title

- OpenUtau/ViewModels/NotesViewModel.cs
Fixed that the playback position is close to the left edge of the window when notes are pasted.
The view is recentered only when the note is off-screen.
> Improved view position when pasting note

- OpenUtau.Plugin.Builtin/EnXSampaPhonemizer.cs
This will Fallback VV's into [V][V] or [V C][CV]
---
- Before, if the vb doesn't have [V V] alias, it will only fallback to [V], this is a problem when it comes to diphthong VV's they will be only monophthongs.
- After, [V V] aliases will fallback to [V][V] or [V C][CV] is the vb doesn't have [V] alias to be a blending VC
> Add Support for VV Split Fallback for Xsampa vb's especially to Delta 5 vbs

- OpenUtau.Core/Classic/ClassicRenderer.cs
- OpenUtau.Core/Classic/Frq.cs
- OpenUtau.Core/Classic/WorldlineRenderer.cs
- OpenUtau.Core/Format/USTx.cs
- OpenUtau.Core/Render/RenderPhrase.cs
- OpenUtau.Core/Ustx/UPhoneme.cs
- OpenUtau/Views/SingersDialog.axaml.cs
https://github.com/stakira/OpenUtau/assets/130257355/014b5d84-8de2-4bb0-b539-65081a56bb9e
- Eliminates pitch differences in crossfades by adding modulation to the pitch curve instead of calculating it in the engine.
- The modulation fades to match the envelope and expands and contracts with velocity.
Internal change: moved code to read frq files.
> Modulation plus

- OpenUtau.Core/DiffSinger/DiffSingerConfig.cs
- OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
- OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.de-DE.axaml
- OpenUtau/Strings/Strings.es-ES.axaml
- OpenUtau/Strings/Strings.es-MX.axaml
- OpenUtau/Strings/Strings.fi-FI.axaml
- OpenUtau/Strings/Strings.fr-FR.axaml
- OpenUtau/Strings/Strings.id-ID.axaml
- OpenUtau/Strings/Strings.it-IT.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Strings/Strings.ko-KR.axaml
- OpenUtau/Strings/Strings.nl-NL.axaml
- OpenUtau/Strings/Strings.pl-PL.axaml
- OpenUtau/Strings/Strings.pt-BR.axaml
- OpenUtau/Strings/Strings.ru-RU.axaml
- OpenUtau/Strings/Strings.th-TH.axaml
- OpenUtau/Strings/Strings.vi-VN.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/Strings/Strings.zh-TW.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
This PR adds support for the next DiffSinger release of Rectified Flow models. This is also a migration from the previous discrete acceleration to the new continuous acceleration.
Major changes:
- DiffSinger rendering depth becomes a float ratio instead of a integer step. This value is 1/1000 of the former value for discrete acceleration.
- DiffSinger speedup is replaced by sampling steps. Old preferences will not be inherited because its definition has changed.
- The `use_shallow_diffusion` key in dsconfig.yaml is renamed to `use_variable_depth`. The old key still takes effects.
- A new `use_continuous_acceleration` key is added into dsconfig.yaml.
- The `max_depth` key in dsconfig.yaml becomes a float for models with continuous acceleration profiles.
- Old cache files will expire due to …
> [DiffSinger] Migrate to continuous acceleration profiles

- OpenUtau.Plugin.Builtin/EnXSampaPhonemizer.cs
- It has come to my attention that I accidentally removed a Teto-specific vowel fallback some time ago (where any instance of ``V`` when combined with ``b`` will fall back to ``@``). This PR fixes this and re-implements the fallback.
- Fixed a split diphthong bug.
- Fixed issue where VV's weren't used in diphthongs.
> [EN X-SAMPA] Vowel fallback bug fixes

- OpenUtau.Core/Classic/Frq.cs
- OpenUtau.Core/Commands/Notifications.cs
- OpenUtau.Core/DiffSinger/DiffSingerVocoder.cs
- OpenUtau.Core/PlaybackManager.cs
- OpenUtau.Core/Render/RenderEngine.cs
- OpenUtau.Core/Util/MessageCustomizableException.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/EditSubbanksViewModel.cs
- OpenUtau/ViewModels/ExpressionsViewModel.cs
- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/ViewModels/PianoRollViewModel.cs
- OpenUtau/ViewModels/SingersViewModel.cs
- OpenUtau/Views/EditSubbanksDialog.axaml.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/MessageBox.axaml.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
Improvement points
- Parts that were not translatable at #1086 can now be translated!
- Added option to hide stack traces (only if seriously unnecessary)
Changes:
- Changed the way to throw translation messages: ErrorMessageNotificationWithTranslation -> MessageCustomizableException
- It is now possible to translate only a part of the text
I have not yet translated all messages.
> Improved translation of error messages for more flexibility

- OpenUtau.Core/Commands/ProjectCommands.cs
- OpenUtau.Core/Render/RenderPhrase.cs
- OpenUtau.Core/Ustx/UExpression.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau.Core/Ustx/UTrack.cs
- OpenUtau/ViewModels/NotePropertiesViewModel.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- When ustx is loaded, expressions that have been deleted from the project are also deleted from the note (because a null expression descriptor in the note causes an error): UNote
- Some expressions that was getting directly from the project are now getting via track (Supplement to #1017)
- ~~When expressions are deleted in ExpressionsDialog, the default required expressions are added again: ProjectCommand
Pending as I don't have a solution for duplicate flags.~~
> Fix deleting expressions

- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
moves the selection logic for default pen to `OnKeyExtendedHandler`
fixes buggy behavior when clicking on the pen tools with the default pen as pen plus
> fix tool selection bug when default pen is pen plus

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Views/MainWindow.axaml.cs
After this change, when dragging an invalid zip file into openutau window, openutau will show an error dialog instead of crashing.
> Fix openutau crash when dragging an invalid zip file into openutau window

- OpenUtau.Core/SingerManager.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PreferencesDialog.axaml.cs
- Fixed singer loading dialog not displaying in preference window.
- When a loading dialog is shown, notification is not used if it is not needed.
- Added error dialog when failed to search singer.
- Changed log message when attaching a singer to a track.
> Fix loading and error dialog

- OpenUtau.Core/Commands/ProjectCommands.cs
- OpenUtau.Core/Format/USTx.cs
- OpenUtau.Core/Ustx/UProject.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
Background:
If the P flag was used in an older project, when opened in a newer version of the OU, the normalize expression is added and the P flag is duplicated.
This function is run automatically and allows us to format old projects without loss of expression.
> Add flag marge function

- OpenUtau.Plugin.Builtin/BaseKoreanPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVVCStandardPronunciationPhonemizer.cs
- Added additional function in BaseKoreanPhonemizer to handle Non-Hangeul graphemes, like *tha*, *thi*, *vyeo*.
- Improved KO CVVC Phonemizer:
1. Completely supports up-to-dated Korean CVVC reclist.
2. Supports Korean Phoneme variation as same level as KO CBNN/CV/DIFFS/ENUNU Phonemizers.
3. Supports Special phonemes(which is purposed to support English Phonemes). CV, VC, VV, CC, Batchim will be generated as same as normal Hangeul phonemes. (for example: "커 rreon 씨" = [keo, eo rr, rreo, eo n, n ss, ssi].)
4. If singer doesn't have some CV phonemes, It flexibly supports alternative phonemes. (like ka, -ka instead of - ka)
5. If singer doesn't have some VC or CC phonemes, it flexibly ignores those VC / CC phonemes. (or use alternative phonemes, like a g instead of a gw)
6. Supports phoneme …
> Improved KO CVVC Phonemizer

- OpenUtau.Core/Render/RenderPhrase.cs
If there are phonemes starting before 0 tick, TemposBetweenTicks will return empty result. After this fix, in this case it will use the tempo of the first tempo marker in the project
> Fix openutau unable to play if the first note starts at 0 tick

- OpenUtau.Core/Enunu/EnunuKoreanPhonemizer.cs
- OpenUtau.Core/KoreanPhonemizerUtil.cs
- OpenUtau.Plugin.Builtin/KoreanCBNNPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVPhonemizer.cs
- Fixed bug in KoreanPhonemizerUtil that generates first consonant " " when have to generate "ㅇ". (in Yeoneum process)
*HandleEmptyFirstConsonant()* in KO CV & KO CBNN Phonemizers became deprecated, so deleted that function.
- Fixed bug in KoreanCBNNPhonemizer that not generates VC with semivowels, like [a gy].
- Should be merged after #1120
> Fixed bug in KoreanPhonemizerUtil, KO CBNN Phonemizer

- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/MessageBox.axaml.cs
- MessageBox.ShowError() always parented to the main window, but now parented to the currently active window.
- Reduce code by using optional arguments.
> Fixed force activation of the main window when an error dialog is shown

- OpenUtau.Core/Ustx/UPart.cs
Fixed an failure to get the relative path from an unsaved project to a wave part when trying to track import with wave part into an unsaved project. Ignore this exception if already got the relative path from the original project.
> Fix importing project into an unsaved project

- OpenUtau/ViewModels/MainWindowViewModel.cs
Fixed OU not launching if project fails to open when attempting to launch OU by double-clicking ustx.
> Fix OU not launching if project fails to open

- OpenUtau.Core/Classic/Ini.cs
- OpenUtau.Core/Classic/Presamp.cs
Fixed a problem in which spaces were not recognized in the “VCPAD= ” line of presamp.ini.
> Fix spaces being ignored in presamp.ini VCPAD

- OpenUtau.Core/Format/MidiWriter.cs
- OpenUtau/ViewModels/MainWindowViewModel.cs
- When importing midi files using DryWetMidi importer, opening midi files or dragging midi files, track names in the midi files will be used as track names and part names in the ustx project.
- When exporting midi files, track names in the ustx project will be used as track names in the midi file.
> Read track names from midi, write track names into midi

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/NotesViewModelHitTest.cs
- OpenUtau/Views/NoteEditStates.cs
- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
PR following #1069 and #1089.
Override vibrato and mod+ by handwriting.
Current Issues:
- For the time being, I use the same icon as the draw pitch tool.
- It becomes difficult to select when there are more tools. It would be nice to organize the tools (like Adobe products) by another modification.
> Add Overwrite Pitch Tool

- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/SingerSetupViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
After this fix, openutau won't crash when trying to install singer from an encrypted archive file. It will show an error dialog.
Encrypted archive isn't supported because the password uses the local encoding of the creator's PC. The archive will be unable to extract by foreign users if the password contains non-ascii characters. We don't encourage the voicebank developers to distribute their voicebank in an encrypted archive file.
related github issue: https://github.com/adamhathcock/sharpcompress/issues/536
related discussion: https://discord.com/channels/551606189386104834/801525671775043625/1162926497988882452
> Fix openutau crash when trying to install singer from an encrypted archive file

- OpenUtau.Core/Classic/Ust.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
- OpenUtau/Views/PreferencesDialog.axaml.cs
- OpenUtau/Views/SingersDialog.axaml
- OpenUtau/Views/SingersDialog.axaml.cs
This is a software for oto that has been popular for a long time.
The first functionality to work with setparam has been implemented.
Right-click on an oto in the Singers dialog, and only that oto can be edited with setParam.
setParam has the ability to edit only limited aliases by selected notes.
I would also like to have the ability to edit the entire oto.ini, but OU and vLabeler can read multiple oto.ini, whereas setParam can only read one oto.ini at a time.
> First linkage with setparam

- OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
- OpenUtau.Plugin.Builtin/JapaneseVCVPhonemizer.cs
- VCV: The CheckOtoUntilHit used in other phonemizers is used here to increase flexibility.
- CVVC: Remove unnecessary codes.
@lottev1991 I thought this code was unnecessary as it will always be true, is this ok?
`(color ?? string.Empty) == color)`
> [JA VCV] Support * あ

- OpenUtau.Plugin.Builtin/JapanesePresampPhonemizer.cs
This PR fixes 2 main things:
- Starting consonants will no longer be inserted before syllables that start with a priority consonant. This is because most priority consonants (usually stops and affricates) are not configured in a way to handle this in Japanese voicebanks (if the end user wishes to include stop consonants anyway, e.g. when they're configured similarly to in Arpasing banks, simply remove them from under the ``[PRIORITY]`` line in the presamp.ini);
- If a voice color does not contain a starting consonant in the oto, it will no longer be inserted (similar to how VC works). Now, it will insert a starting consonant from the main color if it exists, which may give undesired results.
- Adjust VC and starting C length based on tempo changes, similar to #1161. I'm gonna look into …
> [JA Presamp Phonemizer] Some starting consonant fixes/adjustments

- OpenUtau/ViewModels/NotesViewModel.cs
Currently we can use `Ctrl+U` to merge notes, which will join the lyrics of all selected notes together as the lyric of the merged note. After this change, slur lyrics (lyric that starts with `+`) will be ignored. 
If all the notes are slur, it will use the lyric of the first note in selection.
For example:
Original notes: `{a} {+}`
Merged note (before this change): `{a+}`
Merged note (after this change): `{a}`
> Ignore slur lyrics when merging notes with Ctrl+U

- OpenUtau/Controls/NotesCanvas.cs
It is difficult to distinguish between hiragana muddled sounds (e.g., ba-go) and semi-muddled sounds (e.g., pa-go).
Enlarge the piano roll to change the font size.
ひらがなの濁音（ば行等）と半濁音（ぱ行等）の区別が難しいので
ピアノロールを拡大して文字サイズを変更する。
> Changed font size to be calculated in order of height

- OpenUtau.Core/Classic/VoicebankFiles.cs
- OpenUtau.Core/Util/Preferences.cs
Straycat uses .sc.npz to cache frq and WORLD features like MoreSampler's "llsm" file type. this commit simply adds support for it.
> Add support for straycat's cache files

- OpenUtau.Core/Util/TimeAxis.cs
- OpenUtau.Plugin.Builtin/ChineseCVVCPhonemizer.cs
Before this fix, ZH CVVC phonemizer converts between tick and ms only based on the initial tempo instead of the changed tempo. Now it converts them based on the tempo at the position of the note
> ZH CVVC: Fix note timing after tempo change

- OpenUtau.Plugin.Builtin/EnXSampaPhonemizer.cs
- Yet another Kasane Teto fix, decided to just make it a separate boolean;
- Some CV cleanups, hopefully fixes an issue with spaced CVs;
- Fixes a ``ValidateAlias()`` oversight (remember to actually validate aliases if you want to add support for alternate methods, otherwise the code will not work).
> [EN X-SAMPA Phonemizer] Multiple fixes

- OpenUtau.Core/Classic/ExeWavtool.cs
It seems that the characters are garbled if the file encoding of the .bat is utf-8.
This has only been tested on Japanese Windows.
> Fix wavtool not working when full path contains 2 byte characters

- OpenUtau.Core/Render/RenderEngine.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
Prompts to install the Visutal C++ runtime when worldline rendering errors occur.
> Show error message to install Visual C++

- OpenUtau/ViewModels/NotesViewModelHitTest.cs
Before this fix, if the part contains at least 2 render phrases, the pitch drawn with overwrite pitch tool will be misplaced
> Fix pitch misplaced when using overwrite pitch tool

- OpenUtau.Core/Editing/NoteBatchEdits.cs
because they are already baked into the pitch control points
> Clear vibrato and MOD+ after pitch baking

- OpenUtau.Core/Editing/BatchEdit.cs
- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ViewModels/PianoRollViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/MessageBox.axaml.cs
Some batch edits like DiffSinger autopitch may execute really slowly and block the UI. This PR supports running batch edits asynchronously, with a dialog showing progress of the running batch edit.
Major changes:
- Add a property `IsAsync` to `OpenUtau.Core.Editing.BatchEdit` to declare if the batch edit should be run asynchronously.
- Add a method `RunAsync()` to `OpenUtau.Core.Editing.BatchEdit` to run the batch edit asynchronously, with a callback to set the progress and a cancellation token to check if the process is cancelled by user. This method has the same behaviour like `Run()` if not overridden by its implementation classes.
- Adds a static method `ShowProcessing()` to `OpenUtau.App.Views.MessageBox` for running a task in the background and show a modal dialog for manipulating …
> [Help wanted] Support asynchronous batch edits

- .github/workflows/pr-test.yml
If github action test fails on one OS, it will continue to run on other OSs.
> GitHub actions test won't be canceled if it fails on one OS

- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/TrackHeaderViewModel.cs
Since "Open Singers location" is added into the singer menu, I think "Install Singer" should also be added into it, because it is the recommended way for importing singers into OpenUtau for most users
> Add 'Install singer' to singer menu in track header

- OpenUtau/OpenUtau.csproj
See https://github.com/advisories/GHSA-hh2w-p6rv-4g7w for detail
Nuget is preventing any older version of this package from being downloaded, which blocks all our GitHub Actions (and any developer who compiles OpenUtau for the first time)
> Update System.Text.Json to 8.0.4 because of vulnerability

- OpenUtau/Strings/Strings.zh-CN.axaml
There may be mistakes in my translation. For example, "Fail to save..." should be translated as “保存...失败”, but the strings file is not able to move the variable strings to the correct place.
> Updated zh-CN strings

- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/NotesViewModelHitTest.cs
Before this fix, if the part doesn't start at 0 and you right-click on the pitch curve and select "Add point", the added point will be misplaced
> Fix pitch curve 'add point' misplaced

- OpenUtau.Core/Classic/ExeInstaller.cs
Shebang added to the MacOS generated resampler shell file for running resamplers with wine.
> Added Shebang to Generated Shell File.

- OpenUtau.Core/Classic/ExeWavtool.cs
I encountered this error when trying to use an external .exe wavtool on Linux: (the first image shows the original error, and the second shows the error after I marked temp.bat and temp_helper.bat as executable)
The cause was that OpenUtau creates a temporary batch file to run the wavtool and attempts to run it directly, which does not work on Linux because batch files can only run on Windows or through Wine.
This patch fixes it by creating a temporary shell wrapper to run the batch file, but there were a few other changes I had to make to accommodate this, which is described in more detail in the commit messages (there are 5 commits when really there are 2 because I changed one of the commit messages to be worded more clearly). All of the new code is behind checks for OS.IsLinux(), so …
> Fix issue when using exe wavtools on Linux

- OpenUtau.Core/Util/SplitLyrics.cs
- OpenUtau/ViewModels/LyricsViewModel.cs
- OpenUtau/ViewModels/NoteDefaultsViewModel.cs
- OpenUtau/ViewModels/PhoneticAssistantViewModel.cs
The following bugs are fixed:
- In "Edit Lyrics" dialog, pressing Ctrl+Z will result in error. If you click "apply", OpenUtau will crash.
- In "Note Defaults" dialog, press Ctrl+Z in "Default Lyric" field, draw a new note, and OpenUtau will crash
- In "Phonetic assistant" dialog, input a letter, press Ctrl+Z for 3 times and it will show an error
> Fix several bugs on pressing Ctrl+Z in TextBoxes

- OpenUtau.Core/Audio/MiniAudioOutput.cs
the first audio device isn't always available.
> use the first available audio device

- OpenUtau/Views/MessageBox.axaml
Prevents message boxes from sticking out too high.
*For now, the current MaxHeight is a fixed value. Is there a better way to get the maximum value?
> Message box maximum height and scroll bars in place

- OpenUtau.Core/Voicevox/VoicevoxRenderer.cs
- OpenUtau.Core/Voicevox/VoicevoxUtils.cs
* Fixed supportedExp.
* Added volumeExpression.
* Added support for LoadRenderedPitch
* Added hash computed values
* Mute before and after phrases to suppress noise
> VOICEVOX Volume operation F0 read support

- OpenUtau.Core/DiffSinger/DiffSingerBasePhonemizer.cs
The former code loads the dictionary and duration model every time the phonemizer runs (include every single edit on the segments). This PR fixes this bug and the phonemizer no longer stucks.
> Avoid repeated dictionary and model loading in DiffSingerBasePhonemizer

- OpenUtau.Core/Format/MidiWriter.cs
The highest note possible on OpenUtau's piano roll is B9, or midi 131, while the highest note supported by midi standard is 127
Before this change, when exporting a project with such a high note to midi file, OpenUtau crashes. After this change, OpenUtau will ignore these notes.
> Fix openutau crash when exporting midi file with a note above 127

- OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
This PR add checks to ensure all parameters required by the acoustic model are provided by the variance model. If some parameters are missing, OpenUTAU shows an explicit error message instead of throwing an `ArgumentNullException`.
> Improve error message when parameter is missing for DiffSinger acoustic models

- OpenUtau.Core/DiffSinger/DiffSingerBasePhonemizer.cs
- OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
Some inputs of DiffSinger depend on whether the phones are vowels. However, `G2pDictionary.IsVowel()` returns `false` if the phoneme symbol is not found in the dictionary (mostly dsdict.yaml). The rendering continues because the phoneme exists in the phoneme list (mostly phonemes.txt), but produces wrong results because the types of the phonemes are misconfigured. Many people missed some phonemes in their dictionary and had trouble debugging.
This PR adds some checks so that all phonemes should be defined in dictionary if the inputs depend on the phoneme types. If not, OpenUTAU shows an explicit error message.
> Add checks for phoneme definitions in dsdict.yaml

- OpenUtau.Core/KoreanPhonemizerUtil.cs
- `KoreanPhonemizerUtil.cs`uses singer's encoding to read .ini file, but crashing occurs by inproper key reading  when singer's encoding does not support some characters in .ini file. (e.g. When singer's encoding is Shift-jis, but singer's `ko-CV.ini` contains Hangeul characters.)
- So Forced `BaseIniManager`'s read encoding to *utf-8* to handle that issue.
- This change has effects to **Korean CV**, **Korean ENUNU** Phonemizers.
> [KoreanPhonemizerUtil] Fixed crashing when reading ini from non-utf-8 singers

- OpenUtau.Core/OpenUtau.Core.csproj
- OpenUtau.Plugin.Builtin/OpenUtau.Plugin.Builtin.csproj
- OpenUtau.Test/OpenUtau.Test.csproj
- OpenUtau/OpenUtau.csproj
Version 8.0.4 of the JSON NuGet Package has a vulnerability and needs to be updated. Currently, as a result of this, most pull requests will error out and local builds will fail.
> [High priority] Bump JSON package version version to 8.0.5

- OpenUtau.Core/Enunu/EnunuClient.cs
- OpenUtau.Core/Enunu/EnunuConfig.cs
- OpenUtau.Core/Enunu/EnunuEnglishPhonemizer.cs
- OpenUtau.Core/Enunu/EnunuPhonemizer.cs
- OpenUtau.Core/Enunu/EnunuRenderer.cs
- OpenUtau.Core/Enunu/EnunuSinger.cs
- OpenUtau.Core/Enunu/EnunuUtils.cs
- OpenUtau.Core/Render/RenderPhrase.cs
[SimpleENUNUServer0.5.0](https://github.com/rokujyushi/SimpleEnunu/releases/tag/SimpleENUNUServer-0.5.0) is now supported.
Pitch adjustment of melf0 models is now supported.
Velocity and style shifting is now supported.
SimpleENUNUServer version check is now supported.
Client port change and connection expiration time change are now supported.
The following ENUNU and Singer were used to check operation and backward compatibility
ENUNUServer0.6.0
SimpleENUNUServer0.5.0
ENUNU_夏目悠李_ResSkipF0FFConvLSTM_v0.0.1
ENUNU_KanadeShia_NightScene_SiFiGAN_MEL
> Support SimpleENUNUServer0.5.0

- OpenUtau.Core/Format/MidiWriter.cs
Reaper just created one midi file like this, so I fixed it
> Fix openutau failing to import midi if it contains two lyric events at the same time

- OpenUtau.Core/Editing/NoteBatchEdits.cs
Resolve the issue of overlapping adjacent segment pitches between the pitch of the preceding and following SP notes during diffsinger's automatic pitch inference.
> fix diffsinger pitch: pre&tail SP pitch

- OpenUtau/Views/NoteEditStates.cs
Steps to reproduce:
- Launch OpenUtau. Create a project. Create a track. Create a part. Open piano roll.
- Create 3 notes. The first and the last note are valid, while the second one is invalid
- Drag the invalid phonemes's timing bar somewhere, move the preutter point of the next phoneme onto it
- Click here
Before this fix, OpenUtau will crash.
> Fix openutau crashing when trying to edit the preutterence of an invalid phoneme

- OpenUtau.Plugin.Builtin/EnglishVCCVPhonemizer.cs
Makes the VCCV English Phonemizer not confuse [rl] as an onset CC in the word "starlight"
> VCCV EN Starlight Fix

- OpenUtau.Core/Api/G2pDictionary.cs
- OpenUtau.Core/DiffSinger/DiffSingerBasePhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerG2pPhonemizer.cs
This change is made to solve strange bugs caused by G2p, where the phonemizer thought the phoneme is supported but actually it isn't.
- For DiffSinger G2p phonemizers, if the duration uses multi-dict, replacements from bare g2p phoneme to `<langcode>/<phoneme>` will be added by default. No need to have `{from: b, to: en/b}` replacements. 
- When parsing phonetic hints, diffsinger phonemizer will check if the phoneme is supported by duration model before it desides whether to apply language prefix. (this bug made it unable to use DIFFS JA with phonetic hint without prefix such as `[h a]`)
- After running G2p, phonemes unsupported by duration model will be filtered out, which limits the error inside one note before it goes into duration model and affect the whole sentence.
> Diffsinger phonemizers: G2p results add langcode by default; Check if phoneme is supported by duration model

- OpenUtau.Core/MachineLearningPhonemizer.cs
Before this change, if diffsinger phonemizers error on one sentense, all the sentences after it will fail to phonemize. After this change, the following sentences will still be phonemized normally.
> diffsinger phonemizers: error in one sentence won't affect the following sentences

- OpenUtau.Core/Voicevox/VoicevoxRenderer.cs
- OpenUtau.Core/Voicevox/VoicevoxUtils.cs
Fixed problem with tempo changes.
Some variable names have been changed to match.
> VOICEVOXRenderer Tempo change support

- OpenUtau.Plugin.Builtin/ArpasingPlusPhonemizer.cs
> [EN ARPA+] Fix [CCV] lastC and removed some redundant CCV splitter

- OpenUtau.Plugin.Builtin/KoreanCVPhonemizer.cs
`KoreanCVPhonemizer.cs` has been modified.
- The space between the Batchim and the next note can now be removed through the `Use space between the Batchim and the next note` item in `ko-cv.ini`.
- Changed to allow the use of a single sound Batchim (n) instead of the existing VC-style Batchim (a n). (`Use tan Batchim` in `ko-cv.ini`)
- Modified to replace the Batchim `l` with `l` when followed by the initial consonant `r`. (`Use replace the batchim 'L' with 'l' when followed by 'r'` in `ko-cv.ini`)
> Modify KoreanCVPhonemizer.cs

- OpenUtau.Plugin.Builtin/ChineseCVVPlusPhonemizer.cs
Custom features have been added for Chinese CVV.
Added Features
- Configuration file to customize various options such as End Breath, notation, and tail vowels `zhcvvplus.yaml`
- Ability to change the prefix of tail vowels `VowelTailPrefix`
- Option to remove tail vowels for non-vowels longer than a specific length `UseSingleNasalVowel`
- Option to remove tail vowels for Multiple Vowels longer than a specific length `UseSingleMultipleVowel`
- Use of initial alias `UseRetan`
- If the initial alias is only present for certain pronunciations, the missing pronunciations will use the standard alias without the initial alias.
- Ability to modify notations for consonants, Nasal Vowels, Multiple Vowels, and tail vowels `~Dict`
- This allows for the application of additional vowels.
- …
> Add "Chinese CVV Plus Phonemizer"

- OpenUtau/Controls/PropertyEditors/FloatEditor.cs
- OpenUtau/Controls/PropertyEditors/IntEditor.cs
- OpenUtau/Views/ExpressionsDialog.axaml
- OpenUtau/Views/NoteDefaultsDialog.axaml
Before this fix, when inputting invalid number, textbox shows a yellow error message and doesn't respond to further editing. This makes it very hard to input negative value because once you enter the `-`, it errors out
After this fix, it won't show error message and it will allow you to temporarily input invalid numbers. The input will be applied once the text in the textbox becomes a valid number
> When inputting invalid number, textbox won't show yellow error message

- .github/workflows/build.yml
- OpenUtau.Core/OpenUtau.Core.csproj
Upgrades OnnxRuntime and DirectML to more recent versions, fixing some issues with ARM builds. This also brings some general improvements for Diffsinger. Fixes #1346 
Edit: Onnx versions 1.17.0 and above have breaking changes that affect Diffsinger, so upgrading to 1.16.3 instead. Verified it working on macOS x64 and ARM64 versions.
> Upgrade OnnxRuntime and DirectML

- OpenUtau.Core/KoreanPhonemizerUtil.cs
Resolve a warning that happened because "using System.Text;" was written twice in KoreanPhonemizerUtil.cs.
> Resolve a warning

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.de-DE.axaml
- OpenUtau/Strings/Strings.es-ES.axaml
- OpenUtau/Strings/Strings.es-MX.axaml
- OpenUtau/Strings/Strings.fi-FI.axaml
- OpenUtau/Strings/Strings.fr-FR.axaml
- OpenUtau/Strings/Strings.id-ID.axaml
- OpenUtau/Strings/Strings.it-IT.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Strings/Strings.ko-KR.axaml
- OpenUtau/Strings/Strings.nl-NL.axaml
- OpenUtau/Strings/Strings.pl-PL.axaml
- OpenUtau/Strings/Strings.pt-BR.axaml
- OpenUtau/Strings/Strings.ru-RU.axaml
- OpenUtau/Strings/Strings.th-TH.axaml
- OpenUtau/Strings/Strings.vi-VN.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/Strings/Strings.zh-TW.axaml
- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
This adds a Full Screen option under Tools on the main window and under View on the piano roll. It can also be toggled with F11. Translated the string into the languages I know.
Tested on Linux and working there.
> Add Full Screen option

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/Views/PreferencesDialog.axaml
There are more and more preference items. Before this change, we have to scroll down to find the preference item we want. After this changes, the preferences page uses a sidebar for navigation, like how windows settings app does.
Preferences items are also rearranged. The main change is that two new categories, "UTAU" and "DiffSinger" are created for renderer-specified preference items, because some users only use UTAU voicebank or only use DiffSinger voicebanks. Having "UTAU" and "DiffSinger" will make these preference items easier to find.
> Refactor preferences page to using a navigation sidebar, rearrange preference items

- OpenUtau/FilePicker.cs
> When "saving as", or exporting wav, use the filename of the current file by default

- OpenUtau.Plugin.Builtin/ArpasingPlusPhonemizer.cs
just a regular en arpa+ fix, that's all lol
> [EN ARPA+] Fix CCV conditionals with 2 or more consonant clusters

- OpenUtau/ViewModels/ExpressionsViewModel.cs
- OpenUtau/Views/ExpressionsDialog.axaml
Reason.
To batch delete unnecessary expressions after batch addition of expressions from the renderer.
Changes.
Multiple items can now be selected in the ListBox of the ExpressionsDialog.
Items can now be deleted in batches.
> Multi-selection support for ExpressionsDialog.

- OpenUtau/Controls/TrackBackground.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/Views/PianoRollWindow.axaml
Update controls on keyscale change.
> Key scale change function modified.

- .github/workflows/build.yml
Many mac users are still blocked by 'This app is damaged', so I added instructions into our release page which is more noticeable than FAQ.
> Add links to FAQ, and instructions for solving 'This app is damaged' on macOS into release page

- OpenUtau.Core/Format/MusicXML.cs
- OpenUtau.Test/Core/Format/MusicXMLTest.cs
- OpenUtau.Test/Files/MusicXML/61a-Lyrics.musicxml
Before this fix, after importing a musicxml file without tempo, opening the pianoroll will make openutau crash.
> Musicxml: fix crash after importing a musicxml without tempo

- .github/ISSUE_TEMPLATE/feature-request.yml
Though we have QQ group and discord community for feature requests, a github issue template for feature requests is useful because:
- This is is highly requested in the community.
- GitHub issue is better at searching and referencing. For example, searching for "voicing" in discord gives unrelated results containing "voice". Also GitHub issue is googleable
- Some users don't want to create a discord account just to post feature requests.
> Add GitHub issue template for feature requests

- OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
- OpenUtau.Core/DiffSinger/DiffSingerVocoder.cs
- In normal procedure, SHFC only shifts the pitch on variance predictors:
- variance predictor (**shifted pitch**) => acoustic model (original pitch) => vocoder (original pitch)
- If the voicebank has no variance model, SHFC is a no-op.
- With pitch controllable vocoders, SHFC shifts pitch for both variance predictors and acoustic models, meaning synthesizing on shifted pitch and then shift back to original pitch with styles and formants unchanged using the vocoder:
- variance predictor (**shifted pitch**) => acoustic model (**shifted pitch**) => vocoder (original pitch)
> DiffSinger: support SHFC (pitch shift curve)

- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
Set the quantize width to the current grid size instead of a fixed value.
This allows quantization to be done on triplets.
> Change batch edit quantize to grid size

- OpenUtau.Plugin.Builtin/ChineseCVVCPhonemizer.cs
Before this PR, if a syllable contains a short syllabic note and a long slur note, the length of VC part will be very short.
#1391 will be fixed by this PR.
> zhcvvc: length of VC should be based on the whole length of the syllable, including slur notes

- OpenUtau/ViewModels/NotesViewModel.cs
Before this change, when using slice tool, the duration of the part will be extended to 2 * the position where you slice relative to the starting of the part
https://github.com/stakira/OpenUtau/issues/1387 will be fixed by this PR
> fix slice tool extending the part too much

- OpenUtau.Plugin.Builtin/ArpasingPlusPhonemizer.cs
prioritizes spaced variant aliases first before the unspaced ones to avoid conflict with vanilla arpabet vowels
> [EN ARPA+] Add dynamic variations for 'dynMid_vv'

- OpenUtau.Plugin.Builtin/JapaneseCVVCPhonemizer.cs
- OpenUtau.Plugin.Builtin/JapaneseVCVPhonemizer.cs
The current-recommended one is Japanese presamp Phonemizer (JA VCV & CVVC)
> Add "legacy" to the names of JA VCV and JA CVVC phonemizers

- OpenUtau.Core/Commands/Notifications.cs
- OpenUtau/Controls/NotePropertiesControl.axaml.cs
- OpenUtau/ViewModels/SingersViewModel.cs
After making changes to a singer, the Note Properties Panel was not correctly determining if/which part should be reloaded.
> Fix Note Properties Panel not working after auto reloading oto

- OpenUtau.Plugin.Builtin/BaseKoreanPhonemizer.cs
- OpenUtau.Plugin.Builtin/KOtoJAPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanCVCCVPhonemizer.cs
- OpenUtau.Plugin.Builtin/KoreanVCVPhonemizer.cs
- Fixed phonetic hint functionality in the Korean VCV phonemizer. This function got broken a while ago due to some unnecessary lines of code.
- Improved romanization in the Korean VCV Phonemizer. Now it works together with vowel endings, mixed Hangul/romanized notes, and with phonetic hint notes. Before, it only worked together with other romanized notes.
- I added the same functionality to the Korean to Japanese Phonemizer. Now you won't need to type Hangul anymore if you're unable to.
- Fixed some typos in the Base Korean Phonemizer API.
- Implement `MsToTickAt()` in the Korean to Japanese Phonemizer.
> [KO Classic Phonemizers + BaseKoreanPhonemizer] Improve KO romanization + phonetic hint fix + typo fix

- OpenUtau.Core/Ustx/UProject.cs
- OpenUtau/ViewModels/TracksViewModel.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
Use shortcut keys in the pianoroll window to move to the part of the track above or below in the same position.
https://github.com/user-attachments/assets/d9c39628-ada3-40e7-b7d1-cc0115a8c361
This feature does not change the horizontal scroll position of the pianoroll window, and the criterion for whether the part is in the same position is the center of the notes canvas.
- Since voiceParts and waveParts in UProject are explicitly assigned null, I changed them to nullable types to avoid confusion.
- Fixed no scrolling when using End key to move play position.
> Move to the next track part with PageUp/PageDown keys

- OpenUtau.Core/Commands/ExpCommands.cs
- OpenUtau.Core/Ustx/UNote.cs
- OpenUtau.Core/Ustx/UPhoneme.cs
- OpenUtau/Controls/NotePropertyExpression.axaml
- OpenUtau/Controls/NotePropertyExpression.axaml.cs
- OpenUtau/ViewModels/NotePropertiesViewModel.cs
When lyrics or color changes reduced the number of phonemes in a note, old expressions that were no longer needed could cause bugs (e.g. Japanese phonemizer does not work well).
So I have improved that when right clicking on the UI to delete an expression, unwanted expressions with the same abbr in the same note are deleted.
- Remove expression when right-clicking combo box in properties panel - NotePropertyExpression.axaml/axaml.cs
- Changed to remove instead of set the value when the same value as the default value of track expression is selected in the properties panel - NotePropertiesViewModel
- Fixed Phonemizer not running immediately after selecting voice color in properties panel - ExpCommand
- Fixed a case where the expression of the first phoneme of the selected note should be …
> Fixed many expression issues and improved the properties panel

- OpenUtau/ViewModels/TracksViewModel.cs
Before this PR, if the starting position of a part isn't in the current view, when dragging the part, it can only snap to measure line. User can't change the position of the part more precisely. 
After this PR, even if if the starting position of a part isn't in the current view, it can snap to smaller units.
https://github.com/stakira/OpenUtau/wiki/Known-Bugs#part-always-snap-to-measure-line
> Fix part always snapping to measure line if the starting position of a part isn't in the current view

- OpenUtau.Core/Classic/ClassicRenderer.cs
- OpenUtau.Core/Classic/ExeWavtool.cs
- OpenUtau.Core/Classic/SharpWavtool.cs
After this PR, Classic renderer will support DIR (direct) expression like how worldline-r does. It bypasses the resampler and put the original audio into output as-is.
Both builtin wavtools and external exe wavtools (including moresampler) are supported.
> Classic renderer: support direct

- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/ViewModels/PianoRollViewModel.cs
- OpenUtau/Views/EditSubbanksDialog.axaml
- OpenUtau/Views/ExpressionsDialog.axaml
- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/MessageBox.axaml
- OpenUtau/Views/NoteDefaultsDialog.axaml
- OpenUtau/Views/PasteParamDialog.axaml
- OpenUtau/Views/PhoneticAssistant.axaml
- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PreferencesDialog.axaml
- OpenUtau/Views/SingerPublishDialog.axaml
- OpenUtau/Views/SingerSetupDialog.axaml
- OpenUtau/Views/SingersDialog.axaml
- OpenUtau/Views/SliderDialog.axaml
- OpenUtau/Views/TimeSignatureDialog.axaml
- OpenUtau/Views/TrackSettingsDialog.axaml
- OpenUtau/Views/TypeInDialog.axaml
- OpenUtau/Views/VoiceColorMappingDialog.axaml
Changes: ExtendClientAreaToDecorationsHint  is now always false except for splash screen.
Fixed that version, file paths, etc. are not displayed on macOS.
However, I have not been able to test it on an actual device.
Can anyone give me feedback? Or if there is a reason why it shouldn't be modified, please let me know.
> [Waiting for test] Show window title in macOS

- OpenUtau.Core/Classic/ClassicRenderer.cs
- OpenUtau.Core/Classic/ResamplerItem.cs
- OpenUtau.Core/Classic/WorldlineRenderer.cs
- OpenUtau.Core/DiffSinger/DiffSingerCache.cs
- OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
- OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
- OpenUtau.Core/Enunu/EnunuRenderer.cs
- OpenUtau.Core/Render/RenderPhrase.cs
- OpenUtau.Core/Vogen/VogenRenderer.cs
- OpenUtau.Core/Voicevox/VoicevoxRenderer.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.ja-JP.axaml
- OpenUtau/ViewModels/NotesViewModel.cs
- OpenUtau/ViewModels/PianoRollViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
- Keep the cache filenames in each phrase and delete the files of phrases that contain the selected notes (partial filename match).
- Translate progress bar text
I have tested with Classic Singer, but I am not fully aware of the specifications for the other renderers and may not be able to erase all caches.
> Clear caches for each phrase

- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau/Strings/Strings.axaml
Before this PR, OpenUtau only shows "not supported" when trying to load rendered pitch with UTAU voicebanks.
After this PR:
Also enables localization for this message.
> More friendly error message for renderer that doesn't support autopitch

- OpenUtau/Controls/LyricBox.axaml.cs
Fixed problems: 
According to current behavior box.SelectAll() method is called when the LyricBox appears. 
1) The selection may become invisible after modifying the text and changing caret position without saving it (clicking out of the LyricBox). 
2) Sometimes left and right arrow keys are not working properly (when there is selected text).
This problem more noticable when writing Turkish lyrics that are 1 to 8 letters long.
https://github.com/user-attachments/assets/0c2fb586-37d6-4bf1-a512-8969ff3f9488
> Fix textbox caret behavior

- OpenUtau/Views/LyricsDialog.axaml
After openutau updated avalonia, when users paste multiline lyrics into lyrics dialog, only the first line will go into the lyrics dialog, which is fixed in this PR
However, we won't be able to apply lyrics in our lyrics dialog by pressing Enter. 
- If `AcceptsReturn="True"`, we can't catch the "Enter" key event
- If `AcceptsReturn="False"`, we can't paste multiline lyrics
> Fix unable to paste multiline lyrics into lyrics dialog

- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/SplashWindow.axaml.cs
This should fix stuck splash screen on linux when using x11.
> Use available screen if no primary screen is set

- OpenUtau/Program.cs
We can just use the basename, `fc-match`. This should search `$PATH` and is therefore more robust than a hard-coded path. This way distros won't need to patch things like [this](https://github.com/NixOS/nixpkgs/blob/5630cf13cceac06cefe9fc607e8dfa8fb342dde3/pkgs/applications/audio/openutau/default.nix#L51-L53) to prevent null reference exceptions when fontconfig is installed but `fc-match` is not on the hard-coded path.
> Don't use `/usr/bin`, just use `fc-match`

- OpenUtau/Controls/ExpressionCanvas.cs
The default values are difficult to understand and to what extent they are set when there are many editing points on the curve, so a line with default values is drawn.
> Added ability to draw a dash line for the default value of the curve.

- OpenUtau.Core/Classic/VoicebankPublisher.cs
Before this PR, zip file produced by voicebank publisher on windows uses backslash `\`, which won't be recognized as path separator on Mac. Now it uses slash `/` on any platform.
> Zip file produced by voicebank publisher should use slash, not backslash

- OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
- OpenUtau/Views/PreferencesDialog.axaml
Added ability to set different step values for DiffSinger models: **Acoustic**, **Variance** and **Pitch**
This will speed up the rendering and give more options.
According to my experience, only **5** steps are enough to render a good Pitch, while Variance parameters require a value around Acoustic, but can still be much lower if it doesn't contain complex parameters. So I suggest leaving it initially the same as Acoustic, so that the user can change it on their own if they see fit.
> Seperated steps for DiffSinger

- OpenUtau.Core/Commands/ExpCommands.cs
- OpenUtau.Core/DiffSinger/DiffSingerRenderer.cs
- OpenUtau.Core/DiffSinger/DiffSingerSinger.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
- OpenUtau.Core/Editing/NoteBatchEdits.cs
- OpenUtau.Core/Render/IRenderer.cs
- OpenUtau.Core/Ustx/UCurve.cs
- OpenUtau/Colors/Brushes.axaml
- OpenUtau/Controls/ExpressionCanvas.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/Strings/Strings.zh-CN.axaml
- OpenUtau/ThemeManager.cs
- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
DiffSinger acoustic models take actual expression values (rather than delta values) as inputs.
However, as OpenUTAU is originally designed for delta-like expressions, DiffSinger users has been suffering for a long time since they have to tune delta values on an invisible "real curve". Though it seems quite complicated to allow direct editing to the real curve, it could be a positive step to just display it on the expressions panel.
This PR allows user to display and refresh the real curves on their expressions panel. Major changes are:
- `UCurve` class got two new fields, `realXs` and `realYs`. These fields are YAML-ignored.
- `MergedSetCurveCommand` got a new flag parameter `setReal` to indicate whether to update the delta values or the real values
- A new batch edit `RefreshRealCurves` …
> Support displaying real curves from DiffSinger variance predictor

- OpenUtau.Core/Util/PathManager.cs
Ref: https://github.com/stakira/OpenUtau/issues/1459
By using `Environment.SpecialFolder.UserProfile` instead of `Environment.SpecialFolder.Personal` to get user's home directory, this will fix the issue that OpenUtau's folder appearing in `/Users/<username>/Documents/Library` but not `/Users/<username>/Library`.
Since I don't have a matrix to fully test this on a variety of macOS devices, you might want to test it more comprehensively before merging or pushing it to release.
> Fix OpenUtau's data folders appearing in the wrong place on macOS

- OpenUtau.Core/Util/Onnx.cs
Capitalizes CPU, DirectML and CoreML in UI. This was something that was bugging me.
> Capitalize machine learning runner names in UI

- OpenUtau.Core/DiffSinger/DiffSingerBasePhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerARPAPlusEnglishPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerChinesePhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerEnglishPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerGermanPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerItalianPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerJapanesePhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerJyutpingPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerKoreanG2PPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerKoreanPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerPortuguesePhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerRussianPhonemizer.cs
- OpenUtau.Core/DiffSinger/Phonemizers/DiffSingerSpanishPhonemizer.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Controls/PhonemeCanvas.cs
- OpenUtau/Controls/PhonemeUIRender.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/NotesViewModelHitTest.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/PreferencesDialog.axaml
This pull request will add the functionality to optionally obfuscate the DiffSinger language prefix in the phoneme editor. I have personally found this to be an annoyance while using Multi-Dictionary DiffSinger models. DiffSinger recently adopted Multi-Dictionary as the standard for voice library creation, and as such this issue will be present in all DiffSinger models.
This pull request does the following:
- Changes the `GetLangCode()` function in all applicable DiffSinger phonemizers (G2p & Base) to be a public method instead of private, so it can be accessed in `PhonemeCanvas.cs` . This may cause incompatibilities with existing plugin phonemizers, but will not cause any issues with the built-in experience.
- Adds a new toggle switch under the DiffSinger section of the preference window …
> Hide DiffSinger Language Code in Phoneme Canvas

- OpenUtau.Core/Commands/NoteCommands.cs
- OpenUtau.Core/Editing/ResetBatchEdits.cs
- OpenUtau/ViewModels/NotePropertiesViewModel.cs
- OpenUtau/ViewModels/NotesViewModel.cs
- Fixed vibrato volume link not being copied when PasteSelectedParams.
- Fixed volume link not being reset by "Reset vibratos" in batch edit.
- By merging the commands, PasteSelectedParams processing has been sped up.
> Fixed Vibrato VolLink was not copied

- OpenUtau/OpenUtau.csproj
Because netbeauty has a bug that causes OpenUtau unable to launch if it is built with `dotnet publish`. It only works with `dotnet build`.
> Revert "move DLLs to a subfolder"

- OpenUtau/Views/PianoRollWindow.axaml
- OpenUtau/Views/PianoRollWindow.axaml.cs
In the pianoroll window, the up and down keys were being sucked into the menu, but adding RoutingStrategies elements solved this problem.
> Fix Up/Down keys not working

- OpenUtau/ViewModels/NotesViewModelHitTest.cs
- OpenUtau/Views/PianoRollWindow.axaml.cs
Fixed pitch points that overlap with the previous note's pitch curve not being grabbed when the setting allowed only the pitch of the selected note to be edited.
https://github.com/user-attachments/assets/bc45a53e-3284-46ec-9417-547ae7185075
↑
https://github.com/user-attachments/assets/df113402-338a-4d7d-9e47-df439c2e0488
> Improved pitch hit test for overlapping pitches

- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/MainWindow.axaml.cs
Previously scrolling with the mousewheel when hovering over the singer list wouldn't work.
This PR lets you scroll when hovering over the singers list.
(Before scrolling only worked when hovering over the green area, despite the fact that both the red and green regions scroll together)
> Allow scrolling main view when hovering over Singer List

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Views/SingersDialog.axaml
- OpenUtau/Views/SingersDialog.axaml.cs
This PR adds a new button to the Singers dialog located below the spectrogram which plays the currently selected file for quick reference.
> Added play file button to singers dialog

- OpenUtau.Core/Format/USTx.cs
- OpenUtau.Core/Util/MessageCustomizableException.cs
- OpenUtau/ViewModels/TrackHeaderViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
For example, the ustx version error had been replaced by the more abstract “Failed to open file”.
> Fixed translated error messages being overwritten by upper level abstract messages

- OpenUtau/Strings/Strings.axaml
- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/MainWindow.axaml.cs
Since drag and dropping doesn't work on Linux (based on my testing), I think it's better to add "Install Wavtool/Resampler (.exe)" in menu.
> Add "Install Wavtool/Resampler (.exe)" in menu

- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PreferencesDialog.axaml
- Fixed no page transition when opening a project
- Disable ineffective menu on the welcome page
> Fixed unexpected behavior of welcome page

- OpenUtau.Core/DiffSinger/DiffSingerPitch.cs
- OpenUtau.Core/DiffSinger/DiffSingerSinger.cs
- OpenUtau.Core/DiffSinger/DiffSingerVariance.cs
When a path string is `Path.Join`ed with a null value, the result is the original path itself, with no exception raised. In DiffSinger config file, some model path is obtained by joining a directory and a relative path. If the relative path is not given or is null, the result will be a directory rather than a file. When OpenUTAU attempts to read bytes from it, an exception is raised saying "Access to path ... is denied."
This PR adds checks for null relative paths to give user a more understandable message about the root cause.
> [DiffSinger] Fix weired error message

- OpenUtau.Core/Util/Preferences.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/MainWindow.axaml.cs
- OpenUtau/Views/PreferencesDialog.axaml
Imports tempo for new projects, otherwise asks the user.
> Simplifies tempo importing

- OpenUtau.Core/Classic/ExeInstaller.cs
- OpenUtau.Core/Classic/ExeResampler.cs
- OpenUtau.Core/Classic/ExeWavtool.cs
- OpenUtau.Core/Classic/Plugin.cs
- OpenUtau.Core/Classic/ToolsManager.cs
- OpenUtau.Core/Util/Preferences.cs
- OpenUtau.Core/Util/ProcessRunner.cs
- OpenUtau/FilePicker.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/ExeSetupViewModel.cs
- OpenUtau/ViewModels/PreferencesViewModel.cs
- OpenUtau/Views/ExeSetupDialog.axaml
- OpenUtau/Views/PreferencesDialog.axaml
- OpenUtau/Views/PreferencesDialog.axaml.cs
Changes:
- Add Wine Path setting in preferences
- Use Wine directly when rendering using windows only resamplers and wavtools
https://github.com/user-attachments/assets/80186081-3617-41ca-b538-b8bef53b333e
- Add Support for Legacy Plugins on Mac and Linux
https://github.com/user-attachments/assets/70156715-4d30-4113-bcdd-492d7f5db7bc
- Add Support for Wavtools on Mac
Extra:
- Add Unix Executable in FilePicker file types.
---
Special thanks to @kkgarfin for testing this on Mac.
> Use Wine directly instead of wrappers on Mac and Linux

- OpenUtau.Core/Classic/VoicebankLoader.cs
Before this change, if the oto.ini contains two `#Charset:` lines that declare different encodings, OpenUtau will crash. After this change, it will only use the first `#Charset:` line.
(Like the empty ust pr #1594, this is a case that users won't actually meet in daily usage, but it should still be handled correctly rather than crashing the entire OpenUtau.)
> Fix OpenUtau crashing when oto.ini contains two `#Charset:` lines

- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/ExeSetupViewModel.cs
- OpenUtau/Views/ExeSetupDialog.axaml
- Exe Setup Dialog can now be translated.
- Changed to show commands for MacOS in TextBox so that they can be copied.
> Translate Exe Setup Dialog

- OpenUtau.Core/Classic/ClassicSinger.cs
- OpenUtau.Core/Classic/Frq.cs
- OpenUtau.Core/Render/RenderPhrase.cs
- OpenUtau.Core/Ustx/USinger.cs
- Fixed incorrect calculation of cutoffs.
- Faster by not loading the wav to calculate the cutoff length.
- When clear cache, frq are now cleared as well.
- Implemented an interface to allow future reading of pitches from other frequency files.
> MOD+ related bug fixes

- README.md
This PR fixes a broken README link to the Wiki page for ENUNU support.
> Fix broken link to ENUNU wiki page in README.md

- .github/workflows/build.yml
According to https://github.com/actions/runner-images/issues/12677 , NSIS is removed from github actions runner images. So we have to install it in github actions script.
> Install NSIS in github acitons

- OpenUtau.Core/Util/Preferences.cs
Before this fix, `$read` file isn't properly ignored because dollar sign isn't escaped
> escape dollar sign in default gitignore used in publishing singer

- OpenUtau.Plugin.Builtin/Data/Resources.Designer.cs
- OpenUtau.Plugin.Builtin/Data/Resources.resx
- OpenUtau.Plugin.Builtin/Data/kocv.template.yaml
- OpenUtau.Plugin.Builtin/KoreanCVPhonemizer.cs
- Previously, KO CV phonemizer used `ko-CV.ini` as setting file, but many Korean users actually didn't used it. (According to some users' feedback and my observation, many of them didn't know how to use it and used phonemizer with default value.)
- Also `ko-CV.ini` was applied to each voicebanks, not globally.
- And I thought `.yaml` was better than `.ini`, in terms of accessibility and efficiency.
<br>
- So I changed setting files with `ko-cv.yaml`. It works same as `arpasing.yaml`. It uses `kocv.yaml` in Plugin directory by default, but if singer has its own `kocv.yaml` in its directory, it uses singer's yaml instead.
- The lagacy `ko-CV.ini` will be deleted automatically.
<br>
- The variations that Korean CV voicebanks are having is like these:
> Using Rentan(e.g - na) for some …
> [KO CV] Improved behavior, Changed setting file to yaml

- OpenUtau/Views/PianoRollWindow.axaml
Fixed a minor GUI issue when clicking on the tool icon that is already selected, it will lose its highlighting (which I believe is not the intended behavior).
Let's say the pencil tool is currently selected.
You can reproduce this issue by simply clicking on the pencil tool.
Now, the tool icon is no longer highlighted/shadowed. Note that this does not affect the function of the mouse curser, meaning you're still using the pencil tool. This will possibly appear confusing for users to know what tool they're using.
This problem is fixed, making the tool icon keep its highlighting/shadowing after being clicked while already selected.
> Fix note editing tool toggle button behavior

- OpenUtau.Core/Ustx/UCurve.cs
- OpenUtau/Strings/Strings.axaml
- OpenUtau/ViewModels/MainWindowViewModel.cs
- OpenUtau/Views/MainWindow.axaml
- OpenUtau/Views/MainWindow.axaml.cs
Implemented a feature to let you merge/combine multiple vocal parts into one, while preserving the notes, note settings, and expression curves.
Based on an [idea suggestion](https://discord.com/channels/551606189386104834/1087458736777482400) in the OpenUtau Discord server.
Usage: Select two or more vocal parts, right click on any of those parts, and select "Merge parts"
> Add feature to merge vocal parts

- .github/workflows/build.yml
This should fix auto update on Linux since NetSparkle uses gnutar which does not support zips.
Wrapper script that NetSparkle make (Left: tar.gz, Right: .zip)
> Make a tar.gz Linux artifact instead of zip

- OpenUtau/Views/TypeInDialog.axaml.cs
Add accessibility feature suggested by https://github.com/stakira/OpenUtau/discussions/1348
Automatically focus (and select all text) to the textbox when opening dialogs.
> Auto focus to the text field in dialogs
